build.cake, config.json, source/migration/BuildTasks/Xamarin.AndroidX.Migration.BuildTasks.csproj, source/migration/Migration/CecilMigrator.cs, source/migration/Migration/Xamarin.AndroidX.Migration.Core.csproj, source/migration/Tool/Xamarin.AndroidX.Migration.Tool.csproj, tests/AndroidXMigrationTests/Tests/BaseTests.cs, tests/AndroidXMigrationTests/Tests/CecilAssert.cs, tests/AndroidXMigrationTests/Tests/DependenciesTests.cs, tests/AndroidXMigrationTests/Tests/ManagedMigrationTests.cs, tests/AndroidXMigrationTests/Tests/Xamarin.AndroidX.Migration.Tests.csproj
=> Always write as portable pdb

source/AndroidXProject.cshtml
Adds the build targets and tasks to the `buildTransitive/` folder in the nupkg.
Fixes #17
=> Add tasks/targets to buildTransitive

build.cake, mappings/androidx-assemblies.csv, mappings/dependencies.json, source/migration/BuildTasks/Xamarin.AndroidX.Migration.props
- Update the props
- Add a script to automate it
Fixes: #9
=> Update the build to generate the artifacts in the .props

build.cake, source/androidx.mediarouter/mediarouter/transforms/Metadata.xml, source/com.google.android.material/material/transforms/Metadata.xml
AndroidX
Nope
Cake diffs targets. HTML generation + minimal HTML string parsing/replacement analysis (namespaces) to obtain removed, new and moved (derived from removed and new) types for the API
=> preview06 diffs

config.json
This should expose IListenableFuture for AndroidX Work Runtime API
=> Update Guava Dependencies

source/migration/BuildTasks/readme.txt
=> correct repo and url

source/androidx.recyclerview/recyclerview/transforms/Metadata.xml, source/androidx.viewpager2/viewpager2/transforms/Metadata.xml
Testing to see if instead of removing the the setter, we keep the setter and remove the override that is causing issues. As it is an override member, the method will still get called.
Hoping this will fix #58
=> Try another way to resolve the missing setter

config.json
=> Increment the version for Migration

source/migration/JetifierWrapper/src/main/java/com/xamarin/androidx/jetifierWrapper/Main.java
Use UTF-8 when reading files
- Could fix #119
=> [Migration] Use UTF-8 when reading files

config.json, source/androidx.constraintlayout/constraintlayout-solver/Transforms/Metadata.xml, source/androidx.constraintlayout/constraintlayout/Transforms/Metadata.xml
- androidx.constraintlayout.constraintlayout - 2.0.0-beta6 -> 2.0.2
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5387664/Xamarin.AndroidX.ConstraintLayout.dll.breaking.txt) (Only Version value changed)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5387666/Xamarin.AndroidX.ConstraintLayout.dll.diff.txt)
- androidx.constraintlayout.constraintlayout-solver - 2.0.0-beta6 -> 2.0.2
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5392109/Xamarin.AndroidX.ConstraintLayout.Solver.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5392111/Xamarin.AndroidX.ConstraintLayout.Solver.dll.diff.txt)
=> Update ConstraintLayout to 2.0.2.

config.json
- androidx.drawerlayout.drawerlayout (1.0.0 -> 1.1.1)
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5392310/Xamarin.AndroidX.DrawerLayout.dll.breaking.txt) (only parameter name change)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5392312/Xamarin.AndroidX.DrawerLayout.dll.diff.txt)
=> Update DrawerLayout to 1.1.1.

config.json, source/androidx.navigation/navigation-common/Transforms/Metadata.xml
- androidx.navigation.common - 2.2.2 -> 2.3.1
- [diff.txt](https://github.com/xamarin/AndroidX/files/5403374/Xamarin.AndroidX.Navigation.Common.dll.diff.txt)
- androidx.navigation.fragment - 2.2.2 -> 2.3.1
- No API changes
- androidx.navigation.runtime - 2.2.2 -> 2.3.1
- [diff.txt](https://github.com/xamarin/AndroidX/files/5403382/Xamarin.AndroidX.Navigation.Runtime.dll.diff.txt)
- androidx.navigation.UI - 2.2.2 -> 2.3.1
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5403391/Xamarin.AndroidX.Navigation.UI.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5403392/Xamarin.AndroidX.Navigation.UI.dll.diff.txt)
=> Update AndroidX.Navigation.* to 2.3.1.

config.json
- androidx.work.runtime- 2.3.4 -> 2.4.0
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5403160/Xamarin.AndroidX.Work.Runtime.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5403162/Xamarin.AndroidX.Work.Runtime.dll.diff.txt)
=> Update Xamarin.AndroidX.Work.Runtime to 2.4.0.

config.json
androidx.wear.wear - 1.0.0 -> 1.1.0
- [diff.txt](https://github.com/xamarin/AndroidX/files/5409266/Xamarin.AndroidX.Wear.dll.diff.txt)
=> Update AndroidX.Wear to 1.1.0.

config.json, source/androidx.media/media/Transforms/Metadata.Namespaces.xml
- androidx.media.media - 1.1.0 -> 1.2.0
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5412634/Xamarin.AndroidX.Media.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5412635/Xamarin.AndroidX.Media.dll.diff.txt)
- androidx.media.mediarouter - 1.1.0 -> 1.2.0
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5409410/Xamarin.AndroidX.MediaRouter.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5409411/Xamarin.AndroidX.MediaRouter.dll.diff.txt)
=> Update AndroidX.Media and AndroidX.MediaRouter to 1.2.0.

config.json, source/androidx.autofill/autofill/Transforms/Metadata.Namespaces.xml, source/androidx.autofill/autofill/Transforms/Metadata.xml
Context: https://github.com/xamarin/AndroidX/issues/190
androidx.autofill.autofill - 1.1.0-alpha01 -> 1.1.0-beta01
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5490407/Xamarin.AndroidX.AutoFill.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5490409/Xamarin.AndroidX.AutoFill.dll.diff.txt)
=> Update AndroidX.AutoFill to 1.1.0-beta01.

config.json, source/com.google.android.material/material/Additions/Additions.cs, source/com.google.android.material/material/Transforms/Metadata.Namespaces.xml, source/com.google.android.material/material/Transforms/Metadata.xml
com.google.android.material - 1.1.0 -> 1.2.1 rc1
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5518361/Xamarin.Google.Android.Material.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5518362/Xamarin.Google.Android.Material.dll.diff.txt)
Release a preview package of 1.2.1 to let people start playing with the newer bits and see if there are any additional issues.
Known Issues:
- #76
=> Update Com.Google.Android.Material to 1.2.1.

build/scripts/update-config.csx
Script that queries Google's Maven to find the latest stable version of the packages we bind in our `config.json` and outputs a table with currently bound version and latest stable version.  Packages with an asterisk are stable versions we need to update.
If `update` is passed as a parameter to the script, it will automatically update versions in the `config.json` to the latest stable and save it back to disk.
Usage info is documented in the script:
```
// Usage:
//   dotnet tool install -g dotnet-script
//   dotnet script update-config.csx -- ../../config.json <update>
```
Example output:
```
| Package (* = Needs Update)                                   | Currently Bound | Latest Stable   |
|--------------------------------------------------------------|-----------------|---------------- …
```
=> [build] New script to check Google's Maven for new stable package versions

config.json, source/migration/BuildTasks/Xamarin.AndroidX.Migration.props
Should not. Discussed and verified with Matthew.
Not much. Just fixed typos detected with binderator extension tools.
=> migration typos fixes (anroidx -> androidx)

azure-pipelines.yml
=> Only sign on tags

source/androidx.core/core/Transforms/Metadata.Namespaces.xml
=> spelling typo fixed - AndroidX.Core.View.Accessibiity

README.md
N/A
No.
Migration tool code was moved to this repo, updated Migration tool / tasks link in README.md to reflect that.
=> Updated Migration tool link in README.md

samples/NuGet.config
NuGet.config copied for the consistency with GPS-FB repository
=> NuGet.config fix

build.cake, nuget-diff.cake
Changes to get `nuget-diff.cake` to work again.
=> [nuget-diff] Update script.

config.json, mappings/dependencies.json
Update to latest versions of components:
- androidx.security:security-crypto - 1.0.0rc03 -> 1.0.0rc04
-  no API changes 
- androidx.window:window - 1.0.0alpha01 -> 1.0.0alpha05
- [breaking.md.txt](https://github.com/xamarin/AndroidX/files/6325503/Xamarin.AndroidX.Window.dll.breaking.md.txt)
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/6325504/Xamarin.AndroidX.Window.dll.diff.md.txt)
- androidx.work:work-runtime - 2.5.0
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/6325596/Xamarin.AndroidX.Work.Runtime.dll.diff.md.txt)
- androidx.tvprovider:tvprovider - 1.0.0
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/6325648/Xamarin.AndroidX.TvProvider.dll.diff.md.txt)
- androidx.appcompat:appcompat-resources - 1.2.0
- …
=> window-security-bump

mappings/dependencies.json
The dependencies were missing from Window, this should add them?
https://github.com/xamarin/AndroidX/issues/302
=> Add dependencies for window

.github/workflows/new-releases-check.yml, build.cake, global.json, source/AndroidXProject.cshtml, utilities.cake
* search improvements for nuget package
* short artifact id `group_id:artifact_id`
* long/versioned artifact id `group_id:artifact_id:version`
* parameter extraction improvements
* `JavaSourceJar`
* `JavaDocJar`
=> Improvements javadocjar javasourcejar

config.json, mappings/androidx-assemblies.csv
Fixes: #320 
Updateds AndroidX.Window to 1.0.0-alpha07
- androidx.window:window - 1.0.0alpha06 -> 1.0.0alpha07
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/6596816/Xamarin.AndroidX.Window.dll.diff.md.txt)
- org.jetbrains.kotlin:kotlin-stdlib - 1.4.32 -> 1.5.10
- androidx.appcompat.appcompat
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/6596847/Xamarin.AndroidX.AppCompat.dll.diff.md.txt)
- [breaking.md.txt](https://github.com/xamarin/AndroidX/files/6596846/Xamarin.AndroidX.AppCompat.dll.breaking.md.txt)
- androidx.appcompat.appcompat-resources
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/6596854/Xamarin.AndroidX.AppCompat.AppCompatResources.dll.diff.md.txt)
- [breaking.md.txt](https://github.com/xamarin/AndroidX/files/6596853/Xamarin.AndroidX.AppCompat. …
=> Bump androidx.window version

azure-pipelines.yml, config.json, source/Xamarin.Jetbrains.Annotations/Transforms/EnumFields.xml, source/Xamarin.Jetbrains.Annotations/Transforms/EnumMethods.xml, source/Xamarin.Jetbrains.Annotations/Transforms/Metadata.xml, source/Xamarin.Kotlin.Reflect/Transforms/EnumFields.xml, source/Xamarin.Kotlin.Reflect/Transforms/EnumMethods.xml, source/Xamarin.Kotlin.Reflect/Transforms/Metadata.xml, source/Xamarin.Kotlin.StdLib.Jdk7/Transforms/EnumFields.xml, source/Xamarin.Kotlin.StdLib.Jdk7/Transforms/EnumMethods.xml, source/Xamarin.Kotlin.StdLib.Jdk7/Transforms/Metadata.xml, source/Xamarin.Kotlin.StdLib.Jdk8/Transforms/EnumFields.xml, source/Xamarin.Kotlin.StdLib.Jdk8/Transforms/EnumMethods.xml, source/Xamarin.Kotlin.StdLib.Jdk8/Transforms/Metadata.xml, source/Xamarin.Kotlin.StdLib/Additions/InterfacesFixups.cs, source/Xamarin.Kotlin.StdLib/Additions/RangesFix.cs, source/Xamarin.Kotlin.StdLib/Transforms/EnumFields.xml, source/Xamarin.Kotlin.StdLib/Transforms/EnumMethods.xml, source/Xamarin.Kotlin.StdLib/Transforms/Metadata.xml, templates/kotlin/LICENSE.md, templates/kotlin/Metadata.shared.xml, templates/kotlin/Pom.cshtml, templates/kotlin/Project.cshtml, templates/kotlin/Targets.cshtml
Kotlin stdlib is a required dependency of AndroidX.  Thus is needs to be "Microsoft supported".  Today it exists in the "community supported" XamarinComponents.
Moving it to here will enable it to participate in our semi-automated update process to ensure it stays up to date:
- Updates will show up in the automated weekly updates PR
- Updated versions will be automatically consumed by AndroidX instead of needing to manually maintain `dependencyOnly=true` entries
=> Move Kotlin stdlib to this repository from XamarinComponents.

utilities.cake
No.
list of artifacts (with and without versions) task added to utilities
generates markdown tables:
|                                                                      |                                                                      |
|----------------------------------------------------------------------|----------------------------------------------------------------------|
|androidx.activity:activity                                            |Xamarin.AndroidX.Activity                                             |
|androidx.activity:activity-ktx                                        |Xamarin.AndroidX.Activity.Ktx                                         |
|androidx.ads:ads-identifier                                           |Xamarin.AndroidX.Ads.Identifier …
=> list of artifacts AKA bill of material BoM (with and without versions) 

azure-pipelines.yml
This should fix the errors in our build.
=> Update TSA area path since old one no longer exists.

SignList.xml, config.json, source/com.google.crypto.tink/tink-android/External-Dependency-Info.txt, source/com.google.crypto.tink/tink-android/License.md, source/com.google.crypto.tink/tink-android/Transforms/Metadata.Namespaces.xml, source/com.google.crypto.tink/tink-android/Transforms/Metadata.xml, templates/tink/Project.cshtml
Status: Has ~500 binding errors.  Mel to look at fixing them.
=> Bind needed runtime dependency Tink.

mappings/dependencies.json, source/com.google.crypto.tink/tink-android/Additions/Xamarin.Google.Crypto.Tink.Shaded.Protobuf.GeneratedMessageLite.cs, source/com.google.crypto.tink/tink-android/Additions/Xamarin.Google.Crypto.Tink.Shaded.Protobuf.Internal.cs, source/com.google.crypto.tink/tink-android/Additions/Xamarin.Google.Crypto.Tink.Shaded.Protobuf.LazyStringArrayList.cs, source/com.google.crypto.tink/tink-android/Additions/Xamarin.Google.Crypto.Tink.Shaded.Protobuf.MapFieldLite.cs, source/com.google.crypto.tink/tink-android/Additions/Xamarin.Google.Crypto.Tink.Shaded.Protobuf.UnmodifiableLazyStringList.cs, source/com.google.crypto.tink/tink-android/Transforms/Metadata.xml
yes. New bindings (nee packages surfaced)
Continue binding `crypto.tink' artifact
=> crypto-tink-continued

config.json
No.
- nuget packages version bumps
=> nuget version bumps for .NET6 and Java.InterOp version fix

utilities.cake
No.
Cleanup and consolitation of `utilities.cake`. Preparing for adding new "binding improvements" APIs for design and testing.
=> Minor improvements to utilities.cake (consolidation with GPS-FB-MLKit)

azure-pipelines.yml, global.json
=> CI updates - version bumps

build.cake
Context: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/141724/alert/6473245?typeId=7172662
Update SharpZipLib to latest version which includes some security fixes.
=> [build] Use SharpZipLib 1.3.3

build.cake, mappings/androidx-assemblies.csv, mappings/dependencies.json
No
replaced old deprecated cake aliases with new ones
=> fix cake dotnet aliases

build.cake
No.
bumped ANDROID_SDK_VERSION and AndroidSdkBuildTools
=> bumping ANDROID_SDK_VERSION and AndroidSdkBuildTools

config.json
Context: https://github.com/xamarin/AndroidX/issues/519
Context: https://github.com/xamarin/AndroidX/pull/520
Bump all package versions so we can release a full set with all packages marked as `<IsTrimmable>`.
=> Bump all version to release with Trimmable change.

build/scripts/update-config.csx
We needed a quick script to see which of our bound artifacts in `config.json` were already published to NuGet.org.
Added this feature to `update-config.csx` and figured it was worth committing in case we ever need it again.
It's not very efficient, if the package exists it will download the package, but it's good enough for a quick and dirty script.
Example:
```
dotnet script update-config.csx -- ../../config.json published
| Package                                                    | Version           | Status          |
|------------------------------------------------------------|-------------------|-----------------|
| Xamarin.AndroidX.Activity                                  | 1.4.0.3           | Not Published   |
| Xamarin.AndroidX.Activity.Ktx                              | …
```
=> [update-config.csx] Add 'published' command for checking if packages exist on NuGet.org.

config.json, source/migration/Tool/Xamarin.AndroidX.Migration.Tool.csproj
No.
AndroidX Migration tool made net5 and net6 compatible
=> AndroidX Migration tool net5 and net6 multi targeting

.github/workflows/new-releases-check.yml, build/scripts/update-config.csx
Update `update-config.csx` to run on `net6.0`.  Additionally, install .NET 6 instead of .NET 3.1 on our GitHub action that uses this script.
=> [update-config.csx] Update to .NET 6.

azure-pipelines.yml, build.cake, config.json, global.json, source/migration/BuildTasks/Xamarin.AndroidX.Migration.BuildTasks.csproj, source/migration/Tool/Xamarin.AndroidX.Migration.Tool.csproj, tests/AndroidXMigrationTests/Tests/Xamarin.AndroidX.Migration.Tests.csproj
No.
- tools version updates
- nuget version bumps
=> tools updates

LICENSE.md, source/AndroidXProject.cshtml, source/com.google.crypto.tink/tink-android/License.md, source/com.google.j2objc/j2objc-annotations/License.md, source/org.checkerframework/checker-qual/External-Dependency-Info.txt, templates/auto-value/License.md, templates/auto-value/Project.cshtml, templates/gson/License.md, templates/gson/Project.cshtml, templates/guava/License.md, templates/guava/Project.cshtml, templates/kotlin/External-Dependency-Info.txt, templates/kotlin/LICENSE.md, templates/kotlin/Project.cshtml, templates/kotlinx/LICENSE.md, templates/kotlinx/Project.cshtml, templates/reactive-streams/External-Dependency-Info.txt, templates/reactive-streams/License.md, templates/reactive-streams/Project.cshtml, templates/rxjava/License.md, templates/rxjava/Project.cshtml, templates/tink/Project.cshtml
Audit licenses specified in this repository.
Ensure that:
- Every 3rd party license is current
- Every package has a correct `<PackageLicenseExpression>`
- Every package contains a `License.md`
- Every package contains a `THIRD-PARTY-NOTICES.txt`
- Licenses are formatted to ~80 columns for readability
=> Audit license specifications.

config.json
The were several recent changes that affect all NuGet packages in this repository.  We should bump the patch version of every artifact and release them with the updates.
- https://github.com/xamarin/AndroidX/pull/562
- https://github.com/xamarin/AndroidX/pull/554
- https://github.com/xamarin/AndroidX/pull/553
- https://github.com/xamarin/AndroidX/pull/550
=> Bump all the things.

azure-pipelines.yml, workloads.json
No.
1. created `workloads.json` with latest dotnet workloads
this approach needs discussion (different opiniones to use URL or file)
2. Updated CI config (`azure-pipelines.yml`) to use file
=> Using latest Workloads

config.json, source/AndroidXProject.cshtml
No. Only package metadata fixes
Fixed metadata for Compose packages
https://github.com/xamarin/AndroidX/pull/639#issuecomment-1299104374
=> Manual updates 20221107 metadata fixes for compose

SignList.xml
Fix CI release errors:
```
Please update your SignList.xml to include the following unknown files which should be signed: 
D:\a\_work\_temp\artifact-signing\extracted\Xamarin.Build.Download.0.11.4\buildTransitive\Microsoft.Win32.Registry.dll;
D:\a\_work\_temp\artifact-signing\extracted\Xamarin.Build.Download.0.11.4\buildTransitive\Xamarin.Build.Download.dll;
```
=> [SignList.xml] Add entries for Xamarin.Build.Download.

nuget-diff.cake
Generate API diffs in parallel.  
This speeds up the CI time for this step:
| | Sequential | Parallel |
|-|-|-|
| Mac | 12m 39s | 3m 18s |
| Windows | 8m 5s | 3m 27s |
=> [ci] Run api-diffs in parallel.

workloads.json
=> Manual updates 20230314 workload nugets bump

build/ci/build.yml
No. Tooling.
cake downgrade as workaround foc bad IL cake issue
https://github.com/cake-build/cake/issues/3996
=> cake downgrade as workaround for bad IL cake issue

config.json
No.
Bumped recently published packages in order to align [transitivie] dependencies.
=> 20230524 alignment bumps

build/ci/build.yml, build/scripts/update-config.csx, config.json
=> Add `annotation-jvm` dependency to `androidx.annotation.annotation`.

source/androidx.camera/camera-video/Transforms/Metadata.xml
Yes. Managed methodnames surfaced and renamed
Metadata fixes
=> Manual updates 20230709 fix issue 621 Camera.Video

Directory.Build.props, cgmanifest.json, config.json, docs/artifact-list-with-versions.md, published-namespaces.txt, source/com.google.crypto.tink/tink-android/Transforms/Metadata.xml
Yes. Few methods and ctors removed.
Bound new versions of:
- `com.google.crypto.tink:tink-android` - 1.9.0 -> 1.10.0
=> Weekly stable updates 20230721

config.json
No.
updated:
- `org.checkerframework:checker-qual` - 3.36.0 -> 3.37.0
=> Weekly stable updates 20230805

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, published-namespaces.txt, source/com.google.crypto.tink/tink-android/Transforms/Metadata.xml, utilities.cake
Updates to:
- `androidx.databinding:databinding-adapters` - 8.1.2 -> 8.1.3
- `androidx.databinding:databinding-common` - 8.1.2 -> 8.1.3
- `androidx.databinding:databinding-runtime` - 8.1.2 -> 8.1.3
- `androidx.databinding:viewbinding` - 8.1.2 -> 8.1.3
- `com.google.crypto.tink:tink-android` - 1.10.0 -> 1.11.0
- `com.google.android.gms:playservices-wearable` - 18.0.0 -> 18.1.0
=> Weekly stable updates 20231110

Directory.Build.props, cgmanifest.json, config.json, docs/artifact-list-with-versions.md, published-namespaces.txt
Updates
- `androidx.activity:activity` - 1.8.0 -> 1.8.1
- `androidx.activity:activity-compose` - 1.8.0 -> 1.8.1
- `androidx.activity:activity-ktx` - 1.8.0 -> 1.8.1
- `androidx.browser:browser` - 1.6.0 -> 1.7.0
- `androidx.databinding:databinding-adapters` - 8.1.3 -> 8.1.4
- `androidx.databinding:databinding-common` - 8.1.3 -> 8.1.4
- `androidx.databinding:databinding-runtime` - 8.1.3 -> 8.1.4
- `androidx.databinding:viewbinding` - 8.1.3 -> 8.1.4
- `androidx.window:window` - 1.1.0 -> 1.2.0
- `androidx.window:window-java` - 1.1.0 -> 1.2.0
- `androidx.window:window-rxjava2` - 1.1.0 -> 1.2.0
- `androidx.window:window-rxjava3` - 1.1.0 -> 1.2.0
- `org.jetbrains:annotations` - 24.0.1 -> 24.1.0
=> Weekly stable updates 20231117

cgmanifest.json, config.json, docs/artifact-list-with-versions.md
No.
- `com.google.j2objc:j2objc-annotations` - 2.8 -> 3.0.0
=> Weekly Stable Updates 20240315

azure-pipelines.yml, build.cake, build/ci/build.yml, global.json, workloads.json
No.
Bumped tooling versions to latest.
TODO: create new repro PR with dotnet crash
```
#tool nuget:?package=Microsoft.Android.Sdk.Windows&version=34.0.43
```
=> Manual updates 20240410 - tooling version bumps Was #870 (branch name typo)

cgmanifest.json, config.json, docs/artifact-list-with-versions.md
Updated packages
- `androidx.databinding:databinding-adapters` - 8.3.1 -> 8.3.2
- `androidx.databinding:databinding-common` - 8.3.1 -> 8.3.2
- `androidx.databinding:databinding-runtime` - 8.3.1 -> 8.3.2
- `androidx.databinding:viewbinding` - 8.3.1 -> 8.3.2
=> Weekly stable updates 20240412

config.json
No.
Fix for nuget id that was already published.
=> [DO NOT MERGE][PUBLISH FROM BRANCH]  Fix for nuget id for already published nuget

SignList.xml
No.
Updated `SignList.xml` with data for GPS-FB-MLKit packages
=> Update SignList.xml with data from GPS-FB-MLKit

docs/buildtoolsinventory.csv, docs/buildtoolsinventory.md
No.
Updated buildtool inventory
=> Manual Updates 20240930 buildtoolsinventory

util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tests/Xamarin.AndroidBinderator.Tests.csproj, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj
No.
Bumping nugets in some projects. Namely, builds with `net9.0-rc1` revealed several security vulnerabilities:
```
/Users/Shared/Projects/d/X/AX/mu-20240220-tfm-net90/util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj : warning NU1904: Package 'System.Text.Encodings.Web' 4.4.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28
/Users/Shared/Projects/d/X/AX/mu-20240220-tfm-net90/util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Xamarin.AndroidBinderator.Tool.csproj : warning NU1904: Package 'System.Text.Encodings.Web' 4.4.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28
/Users/Shared/Projects/d/X/AX/mu-20240220-tfm-net90/util/Xamarin.AndroidBindera …
```
=> Manual Updates 20241002 SFI nuget bumps

util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/ConfigUpdater.cs
Our code for applying the "1" prefix to GPS packages (ie: `21.0.0` -> `121.0.0`) does not work correctly when the major version is a single digit (ie: `2.0.0`).  When the version is a single digit, the logic was getting skipped, resulting in incorrect version numbers.
=> [update-config] Fix issue with applying GPS prefix to single digit major versions.

build/ci/variables.yml, global.json
=> Manual updates 20241112 - .NET version bumps latest and greatest

source/androidx.media3/media3-session/Transforms/Metadata.xml
- removed 2 `remove-node`
- added necessary fixes to build (parameter types, visibility)
=> Fixes for issue 1067 `androidx.media3.session`

build/ci/variables.yml, global.json
bumped dotnet version for building both locally and on CI
=> Manual updates 20250313 dotnet bumps

config.json
Verified the changes in 07d12d10 allow dotnet/maui to build, so let's release a new version.
=> Bump NuGet version of Xamarin.AndroidX.SavedState
