dotnet/android-libraries

build.cake, source/migration/BuildTasks/CecilfyFiles.cs, source/migration/BuildTasks/Xamarin.AndroidX.Migration.targets, source/migration/Migration/CecilMigrator.cs
This PR makes sure that all the referenced assemblies are available to Cecil as well as making sure that the assembly is saved correctly.
Although this PR appears to have changes all over the show, it actually just changes the loading and saving of the assembly. Previously, I tried to be clever and work all in place - which was unnecessary. I now copy the assembly to the new location first, and then edit it right there.
=> Migration Improvements

source/migration/Migration/CecilMigrator.cs, tests/AndroidXMigrationTests/Tests/BaseTests.cs, tests/AndroidXMigrationTests/Tests/ManagedMigrationTests.cs
Allow migration to continue when symbols are bad.
Fixes #38
Fixes #8
Fixes #79
Fixes #93
=> Allow migration to continue when symbols are bad

config.json, mappings/androidx-assemblies.csv, source/androidx.camera/camera-core/Transforms/Metadata.xml
AndroidX
Yes, just the changes that the CameraX API had.
I've updated the CameraX bindings to 1.0.0-beta05. Particulary, I've updated
- androidx.camera.camera-camera2 to the version 1.0.0-beta05
- androidx.camera.camera-core to the version 1.0.0-beta05
- androidx.camera.camera-lifecycle to the version 1.0.0-beta05
- androidx.camera.camera-extensions to the version 1.0.0-alpha12
- androidx.camera.camera-view to the version 1.0.0-alpha12
=> Update CameraX to version 1.0.0-beta05

config.json
Updates several artifacts to latest stable versions. No breaking changes reported.
Xamarin.AndroidX.Concurrent.Futures (1.0.0 -> 1.1.0) - [diff](https://github.com/xamarin/AndroidX/files/5374033/Xamarin.AndroidX.Concurrent.Futures.dll.diff.txt)
Xamarin.AndroidX.Core (1.3.0 -> 1.3.2) - no changes
Xamarin.AndroidX.CustomView (1.1.0-rc01 -> 1.1.0) - no changes
Xamarin.AndroidX.Emoji (1.0.0 -> 1.1.0) - no changes
Xamarin.AndroidX.Emoji.AppCompat (1.0.0 -> 1.1.0) - no changes
Xamarin.AndroidX.Emoji.Bundled (1.0.0 -> 1.1.0) - no changes
Xamarin.AndroidX.SlidingPaneLayout (1.0.0 -> 1.1.0) - [diff](https://github.com/xamarin/AndroidX/files/5374110/Xamarin.AndroidX.SlidingPaneLayout.dll.diff.txt)
Xamarin.AndroidX.SwipeRefreshLayout (1.0.0 -> 1.1.0) - …
=> Update several artifacts to latest stable versions.

config.json, source/AndroidXSolutionFilter.cshtml
Binderator generates an `AndroidX.sln` file which can be used in Visual Studio, however it contains 104 projects, which does not make VS very happy.  This adds a template to generate solution filter (.slnf) files next to each project file.  This allows you to open only the current project plus its project references in Visual Studio.
=> Generate solution filters for working in Visual Studio.

config.json
- androidx.webkit.webkit - 1.2.0 -> 1.3.0
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5393680/Xamarin.AndroidX.WebKit.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5393681/Xamarin.AndroidX.WebKit.dll.diff.txt)
Most of the "breaking" seems to be renaming classes like `JsReplyProxy` to `JavaScriptReplyProxy` or fields like `UserAgentDarkeningOnly` to `DarkStrategyUserAgentDarkeningOnly`.
=> Update AndroidX.WebKit to 1.3.0.

config.json
android.exifinterface - 1.1.0 -> 1.3.1
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5404236/Xamarin.AndroidX.ExifInterface.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5404237/Xamarin.AndroidX.ExifInterface.dll.diff.txt)
I investigated the breakages since it's `long` -> `Java.Lang.Long` to see if it was an issue with our tooling, but this was really changed by Google, and these are actually different types in Java, so we can't just fix it with metadata.
https://android.googlesource.com/platform/frameworks/support/+/6f437ca8ffec256c8a7ac21f73f17ccd1ab505a0%5E%21/exifinterface/exifinterface/src/main/java/androidx/exifinterface/media/ExifInterface.java
=> Update AndroidX.ExifInterface to 1.3.1.

source/migration/BuildTasks/Xamarin.AndroidX.Migration.targets
AndroidX
No
Context: https://github.com/xamarin/xamarin-android/pull/5195
Due to the way `<Import/>` ordering has changed with .NET 6 workloads,
`$(AndroidApplication)` is not set until after NuGet packages have had
their MSBuild targets evaluated.
The result is `$(_AndroidXShouldRunMigration)` is blank, and
AndroidX.Migration doesn't do any work. We noticed this happening in
MSBuild tests using Xamarin.Forms.Maps.
To solve this issue, we can check for `$(OutputType)` set to `Exe`, as
this is what developers will set in their `.csproj` file.
We may eventually get another MSBuild extension point from dotnet/sdk
to make this possible to fix on the `xamarin-android`-side, but I
think we can simply check both properties for now.
=> [.NET 6] fix for AndroidX.Migration

SignList.xml, config.json
We usually sign all the Mono.* bits, because we usually own it... but not Mono.Cecil.
That is a great library by other great people.
---
Additionally this does a "NuGet-version only" bump to the following "top-level" references used by our templates:
- Xamarin.AndroidX.Annotation
- Xamarin.AndroidX.AppCompat
- Xamarin.AndroidX.Wear is already bumped via https://github.com/xamarin/AndroidX/pull/185 which will go out with these packages.
This will force these packages to be rebuilt with a transitive `Xamarin.AndroidX.Migration >= 1.0.8` dependency which will force the NuGet graph resolution to use this newer version.
=> Sign Mono.Cecil with the third party signature

config.json
- androidx.constraintlayout.constraintlayout - 2.0.2 -> 2.0.4
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5490151/Xamarin.AndroidX.ConstraintLayout.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5490154/Xamarin.AndroidX.ConstraintLayout.dll.diff.txt)
- androidx.constraintlayout.constraintlayout-solver - 2.0.2 -> 2.0.4
- [breaking.txt](https://github.com/xamarin/AndroidX/files/5490160/Xamarin.AndroidX.ConstraintLayout.Solver.dll.breaking.txt)
- [diff.txt](https://github.com/xamarin/AndroidX/files/5490161/Xamarin.AndroidX.ConstraintLayout.Solver.dll.diff.txt)
Additionally this bumps the NuGet version of `androidx.customview.customview` from `1.1.0` to `1.1.0.3`.  This is to fix a mistake in the previous round of updates, where it was changed from …
=> Update ConstraintLayout to 2.0.4.

config.json
Bump the NuGet version of the following packages used by new VS 16.9 templates.  This is due to a previous signing error and we need to ensure nothing is referencing `Xamarin.AndroidX.Migration 1.0.7.1`.
* Xamarin.AndroidX.Legacy.Support.Core.UI
* Xamarin.AndroidX.PercentLayout
=> Bump packages needed for 16.9 template updates.

config.json
Creates a stable release of `Xamarin.Google.Android.Material` 1.1.0.5.  We realize there is still a known bug in this package (https://github.com/xamarin/AndroidX/issues/76), however we want to start binding preview versions of 1.2.1 so users can have the latest features, so we should release a stable version of 1.1.0 first.
=> Release a stable Material 1.1.0.

.github/workflows/new-releases-check.yml
Add a new GitHub Action that:
- Checks for new stable releases in Google's Maven repository every Monday morning.
- If new releases are found, updates the `config.json` with the new versions and opens a PR.
=> [GitHub Actions] New action to periodically check for new stable releases.

source/migration/Migration/CecilMigrator.cs, tests/AndroidXMigrationTests/Tests/JniStringMigrationTests.cs
Some tools generate weird class names:
```csharp
[Register("com/test/test/test/a/b/ʹ$ʹ", DoNotGenerateAcw = true)]
```
This PR will add tests and fix for these cases.
Fixes #209
=> Fix migration issue with obfuscated classes

config.json
We've had `Xamarin.Google.Android.Material` as `rc1` for a few weeks now and there have not been any new reported issues.  We should mark it as `stable` so more people can use it.
=> [material] Mark 1.2.1 as 'stable'.

build.cake, tests/AndroidXMigrationTests/Tests/JetifierTests.cs, tests/AndroidXMigrationTests/Tests/Xamarin.AndroidX.Migration.Tests.csproj
One of the AndroidX migration tests relies on downloading a Facebook SDK from:
```
https://origincache.facebook.com
```
This server no longer seems to exist, disable the test so we can pass tests and publish NuGet packages.
=> [migration-tests] Disable test that relies on no longer available Facebook SDK.

config.json
We released a stable `1.3.0` for `Xamarin.AndroidX.Browser`, however we had already released a `1.3.0.3-alpha01` version which is a higher version.
This bumps the stable version to `1.3.0.3` so it is considered the highest version.
=> Bump Browser NuGet version to be greater than published beta

build/scripts/update-config.csx, config.json
In order to include new Xamarin.Forms templates in Visual Studio, there is a process that downloads every NuGet package referenced by the templates.  Unfortunately it doesn't do normal NuGet resolution; it downloads *every* referenced version of a package instead of just the one that NuGet would resolve.  This creates another issue because the `AndroidX.Migration` version `1.0.7.1` contains an unsigned `Mono.Cecil.dll` assembly which the script also doesn't like.
Unfortunately the dependency tree used by XF is expansive and it isn't really feasible to only update a few packages as was done in #201.  So we have to bump all packages instead.
Additionally updates the `update-config.csx` script to make this revision bump automatically, as well as updates to include a trailing linefeed and …
=> Bump all package revisions to force newer resolution of Migration package.

config.json, source/androidx.camera/camera-camera2/Transforms/Metadata.Namespaces.xml, source/androidx.camera/camera-camera2/Transforms/Metadata.xml, source/androidx.camera/camera-core/Additions/ImageAnalysisBuilder.cs, source/androidx.camera/camera-core/Additions/ImageCaptureBuilder.cs, source/androidx.camera/camera-core/Additions/PreviewBuilder.cs, source/androidx.camera/camera-core/Additions/VideoCaptureBuilder.cs, source/androidx.camera/camera-core/Transforms/Metadata.Namespaces.xml, source/androidx.camera/camera-core/Transforms/Metadata.xml, source/androidx.camera/camera-view/Transforms/Metadata.Namespaces.xml
Fixes #216 
Fixes #233 
When binding `androidx.camera.camera-core`, the interfaces were removed from `AndroidX.Camera.Core.Preview.Builder` to fix some binding errors. This makes the class not usable with the `Camera2Interop.Extender (IExtendableBuilder)` ctor.
I added back the interfaces, which resulted in errors due to covariant return types for methods such as `SetTargetName (string)`.  Instead of changing to return type to JLO to match using metadata, I made an explicit interface implementation that implements the interface.  
This is because the API is designed to be used as a fluent API, and if we change the return type to JLO, it can no longer be used fluently:
```
var previewBuilder = new Preview.Builder()
.SetTargetName ("camera")
.SetTargetAspectRatio (AspectRatio.Ratio43) …
```
=> [camera-core] Add IExtendableBuilder to several *.Builder classes.

source/AndroidXTargets.cshtml
Context: https://github.com/xamarin/xamarin-android/pull/5477
I found that adding the AndroidX packages to a class library adds some
AndroidX `.jar` files to the build output...
Such as:
https://github.com/xamarin/xamarin-android/blob/597e7169b069eff781d8f29ddb7746b719d7f781/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets#L452-L466
I think that we only want to add `.jar` files to Android application
projects. Otherwise, this is attempting to add these files to the
`__AndroidLibraryProjects__.zip` file that is an `EmbeddedResource` of
Xamarin.Android class libraries.
Let's add a `Condition=" '$(AndroidApplication)' == 'true' "`, so that
these `@(AndroidJavaLibrary)` or `@(AndroidAarLibrary)` items are only
added for Xamarin.Android application projects and not class …
=> [msbuild] don't add @(AndroidJavaLibrary) in class libraries

config.json, source/androidx.databinding/databinding-adapters/Additions/Additions.cs, source/androidx.databinding/databinding-adapters/Transforms/EnumFields.xml, source/androidx.databinding/databinding-adapters/Transforms/EnumMethods.xml, source/androidx.databinding/databinding-adapters/Transforms/Metadata.Namespaces.xml, source/androidx.databinding/databinding-adapters/Transforms/Metadata.ParameterNames.xml, source/androidx.databinding/databinding-adapters/Transforms/Metadata.xml, source/androidx.databinding/databinding-common/Additions/Additions.cs, source/androidx.databinding/databinding-common/Transforms/EnumFields.xml, source/androidx.databinding/databinding-common/Transforms/EnumMethods.xml, source/androidx.databinding/databinding-common/Transforms/Metadata.Namespaces.xml, source/androidx.databinding/databinding-common/Transforms/Metadata.ParameterNames.xml, source/androidx.databinding/databinding-common/Transforms/Metadata.xml, source/androidx.databinding/databinding-runtime/Additions/Additions.cs, source/androidx.databinding/databinding-runtime/Transforms/EnumFields.xml, source/androidx.databinding/databinding-runtime/Transforms/EnumMethods.xml, source/androidx.databinding/databinding-runtime/Transforms/Metadata.Namespaces.xml, source/androidx.databinding/databinding-runtime/Transforms/Metadata.ParameterNames.xml, source/androidx.databinding/databinding-runtime/Transforms/Metadata.xml, source/androidx.databinding/viewbinding/Additions/Additions.cs, source/androidx.databinding/viewbinding/Transforms/EnumFields.xml, source/androidx.databinding/viewbinding/Transforms/EnumMethods.xml, source/androidx.databinding/viewbinding/Transforms/Metadata.Namespaces.xml, source/androidx.databinding/viewbinding/Transforms/Metadata.ParameterNames.xml, source/androidx.databinding/viewbinding/Transforms/Metadata.xml
AndroidX
-   androidx.databinding.databinding-adapters - 4.1.2
-   androidx.databinding.databinding-common - 4.1.2
-   androidx.databinding.databinding-runtime - 4.1.2
-   androidx.databinding.viewbinding - 4.1.2
yes. New artifacts.
Bindings of new DataBinding artifacts
See related issues:
https://github.com/xamarin/AndroidX/issues/243
https://github.com/xamarin/xamarin-android/issues/3853
=> DataBinding artifacts

config.json
AndroidX
No, but dependency
Changed nugetId typo
=> AndroidX.Ads.Identifier fixed nugetId typo (was AndroidX.Ads.Idetifier)

config.json
Fixes #229.
When we bind unstable versions previews of Google packages that we already have stable versions of we can no longer push updates to the stable version.  Additionally our dependency generation will cause stable versions of other packages to depend on the unstable version.
This happens for:
* androidx.savedstate.savedstate (1.0.0 and 1.1.0-alpha01)
* androidx.autofill.autofill (1.0.0 and 1.1.0-beta01)
`autofill` will be fixed in #251 because Google has made `1.1.0` the stable version.  This leaves `savedstate`.  We need to revert `config.json` to be the stable version of `savedstate`.  Additionally we need to bump the 3 packages that depend on `savedstate` so they will re-release depending on the stable version.
Going forward we need to not bind preview versions of packages that …
=> Revert `androidx.savedstate.savedstate` to stable version.

config.json
In https://github.com/xamarin/AndroidX/pull/238 we fixed a namespace typo `AndroidX.Core.View.Accessibiity` -> `AndroidX.Core.View.Accessibility`.
These packages depend on types in that namespace, so they need to be bumped so they point to the new namespace.
=> Bump packages affecting by fixing Accessibiity typo fix.

samples/BuildAll/BuildAll.sln, samples/BuildAll/ClassLibrary/Class1.cs, samples/BuildAll/ClassLibrary/ClassLibrary.csproj, samples/BuildAll/ClassLibrary/Properties/AssemblyInfo.cs, samples/BuildAll/ClassLibrary/Resources/values/strings.xml, samples/NuGet.config, source/AndroidXTargets.cshtml
AndroidX
No
Fixes: https://github.com/xamarin/AndroidX/issues/267
A minimal combination of these packages causes a build failure in a
class library:
<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.2.0.6" />
<PackageReference Include="Xamarin.AndroidX.Core" Version="1.3.2.2" />
Fails with:
(_UpdateAndroidResgenAapt2 target) ->
ClassLibrary1\obj\Debug\monoandroid10.0\lp\42\jl\res\color\abc_btn_colored_borderless_text_material.xml(21): error APT2260: attribute alpha (aka ClassLibrary1.ClassLibrary1:alpha) not found.
...
ClassLibrary1\obj\Debug\monoandroid10.0\lp\42\jl\res\color\abc_tint_switch_track.xml(22): error APT2260: attribute alpha (aka ClassLibrary1.ClassLibrary1:alpha) not found.
C:\Program Files (x86)\Microsoft Visual …
=> [msbuild] allow @(AndroidAarLibrary) in class libraries

source/androidx.media2/media2-common/Transforms/Metadata.Namespaces.xml
androidx.media2
No.
namespace typos fixes
=> AndroidX.Media2 namespaces typos fixes

azure-pipelines.yml
ApiDiff shows no differences in API between this and current `master`, so this should be safe to update.
=> Update to Xamarin.Android 16.9.

config.json, mappings/dependencies.json, source/AndroidXProject.cshtml, tests/AndroidXMigrationTests/Tests/DependenciesTests.cs
=> Fixing the typo (missing "arch)"

azure-pipelines.yml, config.json
Currently our CI seems to be producing **different** builds between Windows & Mac:
16.9 - Windows:
16.9 - Mac:
This comparison works against the versions on NuGet.org, so I guess we publish the packages created on Mac to NuGet, which shows no differences.
Unrelated, we should update to the latest XA: 16.10.  Using this version, both Windows & Mac show the same diffs as Windows XA 16.9.  It would seem like the Mac XA 16.9 package was not as recent as the Windows one.
16.10 - Mac
Additionally, let's bump the patch version of the NuGets with diffs, so updated versions will get pushed to NuGet.org, reducing noise on future diffs.
=> [yaml] Update to XA 16.10.

BUILDING.md, README.md
Update and optimize the README to be focused on targeting AndroidX consumers:
- Add FAQs about versioning, time to bind new libraries, and pre-release policy.
- Move repo building instructions to a separate file.
- Remove info about our plans for migration support, as AndroidX is now nearly 3 years old.
=> Update and streamline the README.

azure-pipelines.yml, build/scripts/update-config.csx, config.json, tests/AndroidXMigrationTests/Tests/DependenciesTests.cs
Today, we only consider `compile` dependencies listed in a package's `.pom` and not `runtime` dependencies.  This can lead to instances like https://github.com/xamarin/AndroidX/issues/86 where the `.pom` references were changed from `compile` to `runtime` and we no longer have the proper dependencies.
`androidx.work.work-runtime 2.2.0:`
```xml
<dependencies>
<dependency>
<groupId>com.google.guava</groupId>
<artifactId>listenablefuture</artifactId>
<version>1.0</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>androidx.lifecycle</groupId>
<artifactId>lifecycle-livedata</artifactId>
<version>2.0.0</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>androidx.room</groupId>
<artifactId>room-runtime</artifactId>
<version>2.1.0</version> …
```
=> [build] Enable 'strictRuntimeDependencies'.

azure-pipelines.yml, build.cake, global.json, source/AndroidXProject.cshtml, source/androidx.appcompat/typeforwarders/androidx.appcompat.appcompat-resources-typeforwarders.csproj, source/com.google.android.material/Xamarin.Google.Android.Material.Extensions/Xamarin.Google.Android.Material.Extensions.csproj
Context: https://github.com/xamarin/AndroidX/pull/247
The first step in multi-targeting AndroidX with `net6` is to migrate to `Xamarin.Legacy.Sdk`, which runs on top of .NET 6 but can build `MonoAndroid9.0`.  We'll commit this first to help make it easier to run our diff logic on the resulting packages to make sure there are no regressions.  A future commit will then enable `net6`.
Changes made:
- CI - Install .NET 6 Preview 5
- CI - Install the Android workload
- Change Cake to use `DotNetCore` versions
- Update `Sdk` to `Xamarin.Legacy.Sdk`
=> [build] Convert to Xamarin.Legacy.Sdk.

build/scripts/update-config.csx, config.json
Adding `"excludedRuntimeDependencies": null` to every artifact isn't needed and clutters an already large file.  We can update the `update-config.csx` script to simply omit it when it is the default value (`null`).
```xml
{
"groupId": "androidx.ads",
"artifactId": "ads-identifier",
"version": "1.0.0-alpha04",
"nugetVersion": "1.0.0.5-alpha04",
"nugetId": "Xamarin.AndroidX.Ads.Identifier",
"dependencyOnly": false,
"excludedRuntimeDependencies": null
}
```
=> [update-config] Don't serialize "excludedRuntimeDependencies": null.

source/AndroidXProject.cshtml
Fixes: https://github.com/xamarin/AndroidX/issues/222
The AndroidX package `Xamarin.AndroidX.Annotation` has a dependency on `Xamarin.AndroidX.Migration`.  This means that ~all AndroidX packages have a dependency on Migration, which was crucial during the transition period from AndroidSupportLibraries.
However that transition period is largely over, and we feel we it no longer makes sense to place this package on all AndroidX users.  We cannot remove the dependency for `MonoAndroid90` because it would cause a breakage for many people who rely on it when they upgrade their NuGet versions, but `net6.0-android` is a natural opportunity to make that change.  
Thus, the `net6.0-android` version of `Xamarin.AndroidX.Annotation` no longer has a dependency on `Xamarin.AndroidX.Migration`.  
Note …
=> Do not automatically pull in Xamarin.AndroidX.Migration for NET6.

config.json, source/com.google.android.material/material/Additions/Additions.cs
Fixes https://github.com/xamarin/AndroidX/issues/349
Note that simply changing the parameter names with metadata on the interfaces would change the property names on the `EventArgs` class, which would be a source and binary breaking change.
Instead, I opted to simply add the additional `Item` properties to the `EventArgs` classes as aliases to avoid the breakage.
=> [material] Fix a couple parameter names.

config.json, mappings/dependencies.json, source/androidx.window/window-java/Transforms/EnumFields.xml, source/androidx.window/window-java/Transforms/EnumMethods.xml, source/androidx.window/window-java/Transforms/Metadata.Namespaces.xml, source/androidx.window/window-java/Transforms/Metadata.ParameterNames.xml, source/androidx.window/window-java/Transforms/Metadata.xml, source/androidx.window/window/Transforms/Metadata.Namespaces.xml, source/migration/BuildTasks/Xamarin.AndroidX.Migration.props, utilities.cake
Should the new package be:
- `Xamarin.AndroidX.WindowJava` (in this PR) or 
- `Xamarin.AndroidX.Window.Java` or
- `Xamarin.AndroidX.Window.WindowJava`
I'm not sure what the standard/expectation is...
ALSO, why is the namespace `Androidx` and not `AndroidX` in the NuGet I pulled off the GitHub build system?
AndroidX.Window-1.0.0-alpha10
Updates binding on NuGet `Xamarin.AndroidX.Window`
Adds new NuGet `Xamarin.AndroidX.WindowJava`
Addresses https://github.com/xamarin/AndroidX/issues/356 **Update "AndroidX.Window" to "1.0.0-alpha10"** for Surface Duo and other foldable devices
- androidx.window:window - 1.0.0-alpha09 -> 1.0.0-alpha10
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/7037998/Xamarin.AndroidX.Window.dll.diff.md.txt)
- …
=> Update AndroidX.Window to alpha10

config.json, source/androidx.startup/startup-runtime/Additions/Additions.cs, source/androidx.startup/startup-runtime/Transforms/EnumFields.xml, source/androidx.startup/startup-runtime/Transforms/EnumMethods.xml, source/androidx.startup/startup-runtime/Transforms/Metadata.Namespaces.xml, source/androidx.startup/startup-runtime/Transforms/Metadata.ParameterNames.xml, source/androidx.startup/startup-runtime/Transforms/Metadata.xml, utilities.cake
AndroidX
androidx.startup:startup-runtime - 1.0.0
yes. New artifact.
Bindings of new AndroidX Startup artifacts
https://github.com/xamarin/XamarinComponents/pull/1245
- androidx.window.window - 1.0.0-alpha10 -> 1.0.0-beta01
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/7045927/Xamarin.AndroidX.Window.dll.diff.md.txt)
- [breaking.md.txt](https://github.com/xamarin/AndroidX/files/7045926/Xamarin.AndroidX.Window.dll.breaking.md.txt)
- androidx.startup:startup-runtime -  -> 1.0.0
- [diff.md.txt](https://github.com/xamarin/AndroidX/files/7045882/Xamarin.AndroidX.Startup.StartupRuntime.dll.diff.md.txt)
- [breaking.md.txt](https://github.com/xamarin/AndroidX/files/7045881/Xamarin.AndroidX.Startup.StartupRuntime.dll.breaking.md.txt)
- appcompat resources
- …
=> AndroidX Startup artifact

config.json
fixes #368 cc @moljac @jpobst 
AndroidX.Window-1.0.0-beta02
AndroidX.Window.WindowJava-1.0.0-beta02
No
**Update "AndroidX.Window" to "1.0.0-beta02"** for Surface Duo and other foldable devices
The Xamarin.Android dual-screen samples have been updated and tested with the NuGet generated by this PR build:
https://github.com/microsoft/surface-duo-sdk-xamarin-samples/pull/22
=> Update AndroidX.Window and WindowJava to beta02

azure-pipelines.yml, config.json, source/org.jetbrains.kotlinx/kotlinx-coroutines-android/Transforms/Metadata.xml, source/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/Transforms/Metadata.xml, source/org.jetbrains.kotlinx/kotlinx-coroutines-core/Transforms/Metadata.xml, source/org.jetbrains.kotlinx/kotlinx-coroutines-jdk8/Transforms/Metadata.xml, source/org.jetbrains.kotlinx/kotlinx-coroutines-reactive/Transforms/Metadata.xml, source/org.jetbrains.kotlinx/kotlinx-coroutines-rx2/Transforms/Metadata.xml, templates/kotlinx/External-Dependency-Info.txt, templates/kotlinx/LICENSE.md, templates/kotlinx/Project.cshtml, templates/kotlinx/Targets.cshtml
Updates Kotlin Coroutines to use `binderator`, and moves them to this repository as they are required dependencies of AndroidX and need to be supported by Microsoft.
Notes:
- Fixes the `build`/`buildTransitive` error like was done for Kotlin: https://github.com/xamarin/XamarinComponents/pull/1260
- The dependencies are different.  This is because they changed in Maven, but the old way was manual so they were never updated.  `binderator` automatically populates the dependencies from Maven, so they stay updated.
**Xamarin.KotlinX.Coroutines.Android** (NuGet.org version on left, PR version on right)
**Xamarin.KotlinX.Coroutines.Core**
**Xamarin.KotlinX.Coroutines.Core.Jvm**
**Xamarin.KotlinX.Coroutines.Jdk8**
**Xamarin.KotlinX.Coroutines.Reactive**
**Xamarin.KotlinX.Coroutines.Rx2**
=> Move Kotlin Coroutines to this repository from XamarinComponents.

config.json, source/org.reactivestreams/reactive-streams/External-Dependency-Info.txt, source/org.reactivestreams/reactive-streams/License.md, source/org.reactivestreams/reactive-streams/Transforms/Metadata.xml, templates/reactive-streams/Project.cshtml
Updates ReactiveStreams to use `binderator`, and moves them to this repository, as they are required dependencies of AndroidX and need to be supported by Microsoft.
NuGet.org version on left, PR version on right:
=> Move ReactiveStreams to this repository from XamarinComponents.

azure-pipelines.yml
We have hit an issue using MavenNet in `binderator` when we call `MavenRepository.Refresh ("org.jetbrains.kotlinx")`.  This group id contains 351 artifacts, and `Refresh` limits its search to 100 results.  Our desired artifacts are no longer in the first 100, so they are "not found" when we try to use them.  This has broken our AndroidX build.
This issue has been fixed in the latest MavenNet (https://github.com/Redth/MavenNet/pull/9), so update our binderator to pull in this new MavenNet.
=> [build] Bump to binderator 0.5.0 to fix CI error due to 100 artifact MavenNet limit.

Directory.Build.props, azure-pipelines.yml, source/AndroidXProject.cshtml, source/androidx.appcompat/typeforwarders/androidx.appcompat.appcompat-resources-typeforwarders.csproj, source/com.google.android.material/Xamarin.Google.Android.Material.Extensions/Xamarin.Google.Android.Material.Extensions.csproj
Update our CI build to .NET 6 RC1.
Additional changes:
```
<AndroidGenerateResourceDesigner>false</AndroidGenerateResourceDesigner>
<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
```
=> [build] Update CI to .NET 6 RC1.

SignList.xml, azure-pipelines.yml, config.json, source/com.google.code.gson/gson/Transforms/EnumFields.xml, source/com.google.code.gson/gson/Transforms/EnumMethods.xml, source/com.google.code.gson/gson/Transforms/Metadata.xml, templates/gson/External-Dependency-Info.txt, templates/gson/Project.cshtml
Updates GoogleGson to use `binderator`, and moves it to this repository, as is it a required dependency of AndroidX and need to be supported by Microsoft.
=> Move GoogleGson to this repository from XamarinComponents.

config.json, source/com.google.auto.value/auto-value-annotations/Transforms/Metadata.xml, templates/auto-value/External-Dependency-Info.txt, templates/auto-value/Project.cshtml
Updates Google AutoValue to use `binderator`, and moves it to this repository, as is it a required dependency of AndroidX and needs to be supported by Microsoft.
=> ﻿Move Google AutoValue to this repository from XamarinComponents.

azure-pipelines.yml
#378 is failing because we currently build with d16.10, which does not contain https://github.com/xamarin/java.interop/commit/95c9b79d20791d4f89842564c5e9f0237b516014.
Unfortunately there is no release of d8.11 for VSMac, so there is no officially released version with this fix.  Instead we will pull down matching d16.11/d8.11 CI builds and use them until d17.0 is released.
=> [ci] Bump legacy build package version to 16.11.

build/scripts/update-config.csx, config.json
Update `update-config.csx` with the latest MavenNet that fixed support for `kotlinx-coroutines`, allowing this script to find new versions and mark them as needing updates.
The script will also now apply a consistent sort to the artifacts in `config.json`.
This PR sorts the `config.json` to this new sort.  There should be no changes to the `config.json`, just now sorted alphabetically.
=> [update-config.csx] Update MavenNet to support kotlinx-coroutines.

azure-pipelines.yml
The old version seems to be gone, and replaced with `6.0.100-rc.1.21463.6`.  🤷‍♂️
=> Update .NET 6 RC 1 version

config.json
=> firebase-appindexing net6 dependency update

config.json
Fixes #389 
- Bumps all NuGet versions so new packages will be released
- Bumps Guava dependencies to new `net6.0-android` versions
=> Bump all packages for net6 release.

Directory.Build.props, config.json, source/AndroidXProject.cshtml, templates/kotlin/Project.cshtml, templates/kotlinx/Project.cshtml
Context: https://github.com/xamarin/xamarin-android/issues/6333
In order to put the `.targets` file into Kotlin packages, we use:
```xml
<None Update="@(Model.NuGetPackageId).targets" Pack="True" PackagePath="build\$(TargetFramework);buildTransitive\$(TargetFramework)" />
```
Unfortunately, when we switched to multi-targeting `net6.0-android` using `<TargetFrameworks>` instead of `<TargetFramework>`, `$(TargetFramework)` is now empty when doing the `Pack`.  This means our `.targets` are not getting added to the NuGet, which means the `.jar` file isn't added to users' projects, which results in `Java.Lang.NoClassDefFoundError` errors at runtime.
This means we have to hardcode the desired NuGet directories.  By using a `Directory.Build.props`, we only need to specify them in one place, and …
=> [kotlin] Ensure .targets file gets put into NuGet package.

Directory.Build.props, azure-pipelines.yml
Use Xamarin.Android 12.0 for "classic" bindings.  This should match our .NET 6.0.100 version.
The diffs on this look good.  All the changes are related to more accurate detection of `virtual` vs `override` in `generator`.
Example:
Modified methods:
```diff
-public virtual bool OnInterceptTouchEvent (AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, Java.Lang.Object child, Android.Views.MotionEvent ev)
+public override bool OnInterceptTouchEvent (AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, Java.Lang.Object child, Android.Views.MotionEvent ev)
-public virtual bool OnTouchEvent (AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, Java.Lang.Object child, Android.Views.MotionEvent ev)
+public override bool OnTouchEvent …
```
=> Update Xamarin.Android to d17.0.

azure-pipelines.yml, global.json
Update to build agents with VS2022 instead of VS2019.
This requires a newer version of `Android.Sdk.Legacy` that supports VS2022.
=> Build with 'windows-2022'.

source/androidx.work/work-runtime/Transforms/Metadata.xml
Fixes #424.
Use metadata to fix `WorkRequest.Builder.SetExpedited (...)` so it gets bound:
```
Warning BG8700 Unknown return type 'B' for member 'AndroidX.Work.WorkRequest.Builder.SetExpedited (OutOfQuotaPolicy)'.	
```
CI Built:
=> AndroidX.Work.Runtime: Bind WorkRequest.Builder.SetExpedited.

config.json
Context: https://github.com/xamarin/XamarinComponents/issues/1312
Context: https://github.com/xamarin/XamarinComponents/commit/0874b321e45a400da665f005c46aa54510d13664
Context: https://www.nuget.org/packages/Xamarin.Google.Guava.FailureAccess/1.0.1.5
Context: https://www.nuget.org/packages/Xamarin.Google.Guava.ListenableFuture/1.0.0.5
If you do:
$ mkdir foo ; cd foo
$ dotnet new mauilib
$ dotnet pack
You end up redistributing `com.google.common.util.concurrent.ListenableFuture`
in your MAUI class library NuGet package:
* `foo.1.0.0.nupkg`
* `lib\net6.0-android31.0\foo.aar`
* `libs\78C2212B1AE12Ed.jar`
* `com\google\common\util\concurrent\ListenableFuture.class`
This was fixed in XamarinComponents and pushed to NuGet.org, but we
need to update the AndroidX dependencies for the new …
=> [guava] update Guava dependencies

source/AndroidXProject.cshtml
The `proguard.txt` gets put into an invalid directory when built on the Mac CI.  I assume this is because of directory separator issues:
(Trying to expand this folder in NuGet Package Explorer crashes the program.)
Mac CI build for this PR:
=> Fix proguard.txt being put in invalid path when built on Mac.

azure-pipelines.yml
Context: https://github.com/xamarin/AndroidX/issues/470#issuecomment-1034009432
Previously, we began building our packages with `d17.0` releases.  However, there is no stable VSMac 2022 yet, so we are using preview packages of Xamarin.Android for this on Mac.  The build we are using contains a `Java.Interop.dll, 0.1.2.0` which is incorrect.
Both the Windows and Mac CI builds seem to copy the NuGets they created to the `nuget` archive folder when they complete building.  This is a "last man wins" situation, so if Windows CI takes longer, we release packages built on Windows.  If Mac CI takes longer, we release packages built on Mac (which are broken).
Until we have a stable XA for Mac that builds correct packages, we should disable the Mac lane so packages built on Mac are not published. …
=> Disable Mac CI.

config.json
Context: https://github.com/xamarin/AndroidX/pull/479
Context: https://github.com/xamarin/AndroidX/issues/470#issuecomment-1040741965
We found that some packages are still referencing the incorrect Java.Interop 0.1.2.0.
We have disabled the Mac CI pipeline which should ensure new packages are correct.
In order to ensure all our current published packages are usable, we should bump the patch version of everything and release them.
This also manually bumps `Xamarin.AndroidX.Window.WindowJava` to `1.0.0.7` so that it will be considered newer than the currently published `1.0.0.6-beta04`.
=> Bump all packages to ensure none still reference Java.Interop 0.1.2.0.

azure-pipelines.yml
Context: https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/buildinfraops
As part of ongoing security and compliance efforts:
- Move our Windows builds to the `AzurePipelinesWindows2022compliant` build pool
=> [ci] Build against 1ES's hardened images.

azure-pipelines.yml
I implemented this poorly in XamarinComponents and it breaks other consumers.  It is being worked on but it doesn't currently work.  Revert this for now so that AndroidX is not blocked.
Reverts xamarin/AndroidX#490
=> Revert "[ci] Build against 1ES's hardened images."

azure-pipelines.yml
Attempting to move to the "public" hardened images in `AzurePipelines-EO` has proved problematic because it require non-standard syntax that is not supported on Mac agents, and the `matrix` strategy used by the XamarinComponents templates we use doesn't allow it to only be specified for Windows.
We could bypass this entirely if we had an agent pool that only has a single VM image that is EO compliant.  And we do!  We use `android-win-2022` as a custom pool in Xamarin.Android, and we can reuse it here instead of the "public" images.
Update this repository to use `android-win-2022` pool.
=> [ci] Move CI builds to 1ES's hardened images.

config.json
Our latest package for `Xamarin.AndroidX.Window` is `1.0.0.1`, but there are other packages that appear newer due an incorrect versioning strategy:
Update to `1.0.0.7` so the latest package is on top.
=> Update Xamarin.AndroidX.Window to 1.0.0.7 so it shows as the latest.

azure-pipelines.yml
AndroidX/GooglePlayServices switched to using a private agent pool in order to meet the EO requirements. This pool is elastic, however agents can be reused if they become available while a job is waiting in the queue.
This means that the image may not always be fresh, and the image may contain a newer Xamarin.Android vsix than the one we want to use.  Unfortunately `vsixinstaller.exe` cannot downgrade an installed package, which causes us to build with the newer one instead of our intended one.
A new command was added to `boots` (`--downgrade-first`) which will first revert the installed Xamarin.Android vsix to the one that shipped with the target version of Visual Studio.
Update to the latest preview of `boots`, and call the new command.
Also switches to `dotnet tool update` which can …
=> [ci] Update boots to fix vsix downgrade issue

Directory.Build.props
Fixes: #519
In Xamarin.Android Classic we link all assemblies by default unless the user opts out.  In .NET6+, assemblies must opt-in to being linked by setting `$(IsTrimmable)`.
We already had this for packages using the default AndroidX template, but AndroidX dependencies (like Kotlin) bound in this repository use other templates that did not include trimming.
Enable trimming via `Directory.Build.targets` to ensure it affects *all* assemblies.
From CI build for `Xamarin.Kotlin.Stdlib.dll`:
=> Mark all assemblies as Trimmable via Directory.Build.props.

config.json
Before we realized the issues caused by `AndroidX.Core` 1.7.0, we published packages using that version, including `1.7.0.1`.  After we realized the issue, we reverted our package versions back to `1.6.x` and delisted the packages from NuGet.
https://github.com/xamarin/AndroidX/issues/439
However, now that we are back on a fixed `1.7.0`, we are trying to release packages that have the same versions (ie: `1.7.0.1`) as the delisted packages on NuGet, which is not permitted.
Therefore we need to bump these packages again to be "newer" versions than the delisted packages instead of conflicting with them.
=> Bump packages to be higher than previously released unlisted packages.

build.cake, config.json, source/com.google.guava/failureaccess/Transforms/Transforms.xml, source/com.google.guava/failureaccess/Xamarin.Google.Guava.FailureAccess.targets, source/com.google.guava/guava/Transforms/Transforms.xml, source/com.google.guava/guava/Xamarin.Google.Guava.targets, source/com.google.guava/listenablefuture/Transforms/Transforms.xml, source/com.google.guava/listenablefuture/Xamarin.Google.Guava.ListenableFuture.targets, templates/guava/External-Dependency-Info.txt, templates/guava/License.md, templates/guava/Project.cshtml
This incorporates some stuff from https://github.com/xamarin/AndroidX/pull/395 in order to complete migrating Guava from XamarinComponents to the AndroidX repository.
Some notes:
- We use `excludedRuntimeDependencies` to ignore Guava's dependencies.  They use the "parent POM" pattern which we currently do not support, which causes `binderator` to throw an `NRE`.  We use explicit `<PackageReference>`'s for now to incorporate these dependencies.
- Removes `Xamarin.CodeHaus.Mojo.AnimalSnifferAnnotations` as a Guava dependency, as this is not present in the POM.
- To simplify PR (and because we can't use `binderator` for dependency management currently), does not import `Xamarin.Google.J2Objc.Annotations` or `Xamarin.CheckerFramework.CheckerCompatQual` to this repo yet.
- Note …
=> Import Guava to AndroidX repository

azure-pipelines.yml, build/scripts/update-config.csx, config.json, source/com.google.j2objc/j2objc-annotations/External-Dependency-Info.txt, source/com.google.j2objc/j2objc-annotations/License.md, source/org.checkerframework/checker-qual/External-Dependency-Info.txt, source/org.checkerframework/checker-qual/License.md, templates/guava/Project.cshtml, templates/no-bindings/Project.cshtml, templates/no-bindings/Targets.cshtml
Switches dependencies for `Xamarin.Google.Guava` from being manually managed with `<PackageReference>` in `.csproj`, to being automatically generated from `config.json`.  This will help ensure its dependencies are kept updated and correct with its `.pom` file.
Status:
- ✅ Uses parent POM dependencies instead of manual dependencies
- ✅ `Xamarin.Google.Code.FindBugs.JSR305` is in GPS (eventually should probably move here)
- ✅ `Xamarin.Google.ErrorProne.Annotations` is in GPS (eventually should probably move here)
- ✅ `Xamarin.Google.J2Objc.Annotations` is moved from XamarinComponents (updated to `MonoAndroid12.0`)
- ✅ `org.checkerframework.checker-qual` has been bound
- Note that Guava was previously incorrectly depending on `checker-compat-qual` rather than `checker-qual`, thus …
=> Use parent POM to support Guava dependencies.

azure-pipelines.yml, source/Xamarin.Kotlin.StdLib/Transforms/Metadata.xml
Updates CI to build with:
- Classic: VS2022 17.2
- .NET 6: Maui RC3
Types of reported API differences:
(Previously needed Metadata.xml to fix this issue has been removed.)
Example:
```
Removed method:
public static bool Contains (int[] arg0, int element);
Added method:
public static bool Contains (int[] arg0, uint element);
```
Example:
```
Removed method:
public static int TakeUpperBits (int obj, int bitCount);
```
[Kotlin source](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/src/kotlin/random/Random.kt#L374-L376)
```
internal fun Int.takeUpperBits(bitCount: Int): Int =
this.ushr(32 - bitCount) and (-bitCount).shr(31)
```
Example:
```
Modified methods:
-public abstract Java.Lang.Object Yield (Java.Lang.Object p0, Kotlin.Coroutines.IContinuation p1)
+public abstract …
```
=> [ci] Update to Classic 17.2 / .NET 6 RC3.

source/AndroidXProject.cshtml, source/androidx.appcompat/typeforwarders/androidx.appcompat.appcompat-resources-typeforwarders.csproj, source/com.google.android.material/Xamarin.Google.Android.Material.Extensions/Xamarin.Google.Android.Material.Extensions.csproj, source/migration/Tool/Xamarin.AndroidX.Migration.Tool.csproj, templates/kotlin/Project.cshtml
Fixes warning produced for each created package by using `<PackageIcon>` instead of deprecated `<PackageIconUrl>`:
```
C:\Program Files\dotnet\sdk\6.0.300\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,
5): warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' eleme
nt instead. Learn more at https://aka.ms/deprecateIconUrl [C:\code\AndroidX\generated\androidx.activity.activity\androi
dx.activity.activity.csproj]
```
Example:
=> Use <PackageIcon> instead of deprecated <PackageIconUrl>.

Directory.Build.props, source/migration/Dummy/Xamarin.AndroidX.Migration.Dummy.csproj
Use `<Nullable>enable</Nullable>` in `Directory.Build.props` to enable nullable reference type annotations for packages in this repo.
Note that NRT annotations are pulled from the `.jar` files we bind.  We will not make manual fixes to them if they are incorrect or missing.
=> [Directory.Build.props] Turn on NRT annotations.

azure-pipelines.yml
Because the "verify published namespaces" step currently runs before the "api-diff" step, if there are new namespaces the build will error and not produce the api diffs.  These diffs can be useful to help determine where the new namespaces are coming from.
By running the verification after api-diff, we can have information from both steps available for review.
=> [ci] Verify published namespaces after api-diff has run.

azure-pipelines.yml, build.cake, samples/BuildAll/BuildAll.sln, samples/BuildAll/BuildAllDotNet.sln
Re-enables Mac CI builds, which were previously disabled due to lack of VSMac 2022 stable releases.
Adding `BuildAllDotNet.csproj` to `BuildAll.sln` does not seem to work on Mac, as Mono cannot build the .NET 6 project:
```
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): 
error : Invalid framework identifier ''.
```
Fix by creating a separate `BuildAllDotNet.sln` which is built with `dotnet build`.  Add this step to cake.
=> Re-enable Mac CI builds.

azure-pipelines.yml, workloads.json
Update:
- .NET 6 to `6.0.400`
- `microsoft.net.sdk.android` workload to `32.0.448`
- Classic to VS `17.3` versions (XA `13.0`)
Remove extraneous `UseDotNet` task now that we no longer use both `3.1` and `6.0`.  The base template will install `$(DotNetVersion)` for us.
- No API changes, as expected
=> Update dotnet to `6.0.400` and legacy to `17.3`.

build/scripts/update-config.csx, config.json
We recently [added](https://github.com/xamarin/AndroidX/pull/556) a binding for `Xamarin.Google.Android.InstallReferrer`.  However, we only bound version `1.0.0` because it was `Apache 2.0` licensed.  Newer versions of this package are licensed as 	`Android Software Development Kit License` and thus we cannot bind them without reworking the package to use XBD.
However, our update script is going to see the newer version every week and attempt to automatically update it.  Eventually we will forget and approve it, which will put us out of license compliance.
As a fix, add a new feature to the update script where an artifact can be marked as `"frozen": true`.  When an artifact is marked like this the update script will not attempt to update the package.  Additionally, the package will be …
=> [update-config.csx] Add ability to "freeze" updates for an artifact.

config.json
We released a [preview version](https://www.nuget.org/packages/Xamarin.AndroidX.Core.SplashScreen/1.0.0.1-rc01) of `androidx.core.core-splashscreen` as version `1.0.0.1-rc01`.
However, we released the final version as `1.0.0`, which is considered *before* `1.0.0.1-rc01`, and thus the preview version is listed as the "highest" available version on NuGet:
Bumping the stable version to `1.0.0.1` will make it the "best" version.
=> Bump `androidx.core.core-splashscreen` NuGet version to `1.0.0.1`

azure-pipelines.yml
In order to meet DevDiv "secure supply chain" requirements for CI machines that build software that is shipped, we need to use some special VM images that have been "locked-down" further than the publicly available Azure Pipelines images.
Our Windows `android-win-2022` image already meets this requirement.
This PR updates the Mac image to `internal-macos12` to meet this requirement.
As a side-effect, it looks like this image is twice as fast??!??
Mac Build: `103 min` -> `57 min` 🎉🥳🎈
=> Use internal locked-down Mac VM image for building.

azure-pipelines.yml
When calling commands sequentially in Powershell, the exit code for the script is the exit code for the last called command.  Thus when installing our `android`/`maui` workloads with these 3 commands:
```
dotnet workload update --verbosity diag --from-rollback-file $(XamarinDotNetWorkloadSource) --source $(Dotnet6Source) --source $(NuGetOrgSource)
dotnet workload install maui --verbosity diag --skip-manifest-update --source $(Dotnet6Source) --source $(NuGetOrgSource)
dotnet workload update
```
The `dotnet workload install maui` command fails, but the final command succeeds, thus the CI step is marked as success and the build continues:
```
No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
Invalid …
```
=> [ci] Fail build if .NET android/maui workloads cannot be installed.

azure-pipelines.yml, global.json
I _think_ I've figured out what breaks our CI every month...
We explicitly install a specific version of .NET in our CI pipeline:
```
DotNetVersion: 6.0.401
```
We also explicitly request versions of the workloads that are designed to work with that .NET version:
```json
{
"microsoft.net.sdk.android": "32.0.465/6.0.400",
"microsoft.net.sdk.ios": "15.4.454/6.0.400",
"microsoft.net.sdk.maccatalyst": "15.4.454/6.0.400",
"microsoft.net.sdk.macos": "12.3.454/6.0.400",
"microsoft.net.sdk.tvos": "15.4.454/6.0.400",
"microsoft.net.sdk.maui": "6.0.540/6.0.400",
"microsoft.net.workload.mono.toolchain": "6.0.9/6.0.400",
"microsoft.net.workload.emscripten": "6.0.9/6.0.400"
}
```
However our `global.json` contains `"rollForward": "latestMinor"`:
```json
"sdk": 
{
"version": "6.0.401",
"rollForward": …
```
=> [global.json] Use `"rollForward": "patch"`.

build/ci/build.yml
The way our classic XA VSIX installer works is it cannot downgrade from a higher version.  To solve this, we always first revert the VSIX to the version that ships with the installed version of Visual Studio, and then we can install our version on top of that.
Unfortunately, when our build agent images are updated to a newer version of VS than our VSIX, we cannot install our older version.
Thus, since our agents have been updated to VS 17.4, trying to install our 17.3 XA VSIX fails and the 17.4 version remains.
Mac does not suffer from this issue, so we are currently building with different versions on Windows and Mac:
Mac - Our pinned 17.3 pkg
Windows - 17.4 VSIX that ships with Visual Studio 17.4
Update both our installers to d17.4 so that both platforms are producing the same output.
=> [ci] Bump classic XA to 17.4.

build/ci/setup-environment.yml
The new CI pipeline didn't include the `boots --downgrade-first` option needed to ensure the classic XA VSIX is properly installed on Windows: https://github.com/xamarin/AndroidX/pull/513.
Without this, the VSIX fails to install if there is already a newer VSIX on the build agent:
```
12/5/2022 10:06:50 PM - An extension with a matching Identifier is already installed to this product.
12/5/2022 10:06:50 PM - Microsoft.VisualStudio.ExtensionManager.AlreadyInstalledException: This extension is already installed to all applicable products.
at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
at VSIXInstaller.ExtensionService.GetInstallableData(String …
```
=> [ci] Add back boots `--downgrade-first` option to ensure VSIX is installed correctly.

build.cake, build/ci/build-and-test.yml
Move building packages and building samples into separate CI steps so building packages can succeed and run other CI steps even if the samples step fails.
This is accomplished with new `ci-build` and `ci-samples` Cake targets.  All existing targets continue to function the same as they always have.
=> [ci] Separate building packages and building samples into separate steps.

.github/workflows/new-releases-check.yml
No. Changed scheduled job to start at Friday instead of Monday.
=> schedule new releases on friday instead of monday

utilities.cake
No.
licenses added for new packages w/o license info for component governance
=> component governance fixes - licenses added for new packages w/o license info

Directory.Build.props, source/AndroidXProject.cshtml, source/androidx.appcompat/typeforwarders/androidx.appcompat.appcompat-resources-typeforwarders.csproj, templates/accompanist/Project.cshtml, templates/auto-value/Project.cshtml, templates/dev-chrisbanes-snapper/Project.cshtml, templates/flogger/Project.cshtml, templates/gson/Project.cshtml, templates/guava/Project.cshtml, templates/installreferrer/Project.cshtml, templates/kotlin/Project.cshtml, templates/kotlinx/Project.cshtml, templates/napier/Project.cshtml, templates/no-bindings/Project.cshtml, templates/reactive-streams/Project.cshtml, templates/rxjava/Project.cshtml, templates/tink/Project.cshtml
Although we don't currently build and ship AndroidX for `net7.0` or `net8.0`, it is a good test exercise to run `generator` against AndroidX to ensure we aren't creating any regressions in `generator`.
To do this, we currently have to change the `TargetFrameworks` in ~16 templates.
Instead, let's put the default `TargetFrameworks` to build in `Directory.Build.props`, so it only has to be changed in one place.
Note that projects (like `Xamarin.AndroidBinderator.csproj`) can continue to explicitly specify their TF(s) if they need to.
=> [Directory.Build.props] Add $(_DefaultTargetFrameworks).

.github/workflows/new-releases-check.yml
No.
GitHub actions fail to run, because of outdated actions using Node v12. New updated actions use Node v16.
```
[build](https://github.com/xamarin/AndroidX/actions/runs/4635871484/jobs/8203265833#step:6:105)
GitHub Actions is not permitted to create or approve pull requests.
[build](https://github.com/xamarin/AndroidX/actions/runs/4635871484/jobs/8203265833)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-dotnet@v1, peter-evans/create-pull-request@v3. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> github actions updates

source/AndroidXTargets.cshtml
A customer reported a build error such as:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\targets\Microsoft.Android.Sdk.AndroidLibraries.targets(77,5):
error XACAAR7014: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at System.Text.StringBuilder.ToString()
at Xamarin.Android.Tasks.CreateAar.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute()
Somewhere here:
https://github.com/xamarin/xamarin-android/blob/c31f3eda63a16e412a39fa61eb0f885be3c5f543/src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs#L108-L114
The problem appears to be triggered by:
ProguardConfigurationFiles=
~\.nuget\packages\xamarin.androidx.versionedparcelable\1.1.1.15\buildTransitive\net6.0-android31.0\..\..\proguard\proguard.txt …
=> [msbuild] only include `@(ProguardConfiguration)` in apps

util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Xamarin.AndroidBinderator.Tool.csproj, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/MavenArtifactConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj
There are instances where we want to add a dependency to a package that is not specified in a library's POM file.
For example:
- https://github.com/xamarin/AndroidX/issues/727#issuecomment-1539066555
- https://github.com/xamarin/AndroidX/blob/main/source/AndroidXProject.cshtml#L179-L208
Because we do not currently have support for this, we have to hardcode `@if { }` blocks to the `.csproj` template each time we want to do this.
Instead, this commit adds support for `extraDependencies` in the `config.json`, for example:
```json
{
"groupId": "androidx.annotation",
"artifactId": "annotation",
"version": "1.6.0",
"nugetVersion": "1.6.0.1",
"nugetId": "Xamarin.AndroidX.Annotation",
"dependencyOnly": false,
"extraDependencies": "com.google.errorprone.error_prone_annotations"
}
```
Which …
=> [Binderator] Add support for `extraDependencies`.

build/ci/build.yml
No. Tooling  updates for CI.
Context:
CI builds fail
https://github.com/xamarin/GooglePlayServicesComponents/pull/794/checks?check_run_id=15026919516
The reason is older version of `xamarin.androidbinderator.tool`
```
Starting: Install tool: xamarin.androidbinderator.tool
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program …
```
=> Manual updates 20230714 ci tools updates

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, source/androidx.appcompat/appcompat-resources/Additions/AndroidX.AppCompat.Graphics.Drawable.DrawableContainer.cs, source/androidx.appcompat/appcompat-resources/Additions/AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper.cs, source/androidx.appcompat/appcompat-resources/Additions/readme.md
Yes. Adds 2 classes that were removed by google (replaced with alternatives)
- dummy Addtions classes added to prevent Reflection, Mono.Cecil, AOT - linking errors in general
- `AndroidX.AppCompat.Graphics.Drawable.DrawableContainer`
- `AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper`
- classes are marked with `Obsolete` attribute
Should fix MAUI/Xamarin.Forms issues:
*   https://github.com/dotnet/maui/issues/16074
Including specific android libraries via nuget causes AOT failures on RELEASE build #16074
*   https://github.com/xamarin/Xamarin.Forms/issues/15668
[Bug] Updating Xamarin.AndroidX.AppCompat to 1.6.0 causes ReflectionLoadException #15668
*   https://github.com/xamarin/AndroidX/issues/690#issuecomment-1414325720
Mono.Cecil.ResolutionException: Failed to resolve …
=> Fix for AndroidX.AppCompat AOT/Reflection/Linking errors

util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Xamarin.AndroidBinderator.Tool.csproj, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj
Context: https://github.com/xamarin/AndroidX/pull/773
We have an artifact that specifies a dependency that we cannot automatically figure out the version to (likely due to unsupported parent POMs).
We would like to work around this by ignoring the bad dependency with `excludedRuntimeDependencies`, and then adding it back with `extraDependencies`, which will use the dependency version specified in the config file:
```
"groupId": "androidx.wear.protolayout",
"artifactId": "protolayout-expression",
"excludedRuntimeDependencies": "org.jetbrains.kotlin.kotlin-stdlib",
"extraDependencies": "org.jetbrains.kotlin.kotlin-stdlib",
```
However, the way we currently process this, the dependency gets excluded because the "excludes" are processed after the "extras".
Rework the logic so we run the …
=> [binderator] Allow `extraDependencies` to specify an `excludedDependency`.

build/ci/setup-environment.yml
No. Infrastructure.
While waiting for release of Cake 3.2.0, let's use Cake.Tool preview
https://github.com/cake-build/cake/pull/4206
https://github.com/cake-build/cake/pull/4206#issuecomment-1742215387
https://dev.azure.com/cake-build/Cake/_artifacts/feed/cake/NuGet/Cake.Tool/overview/3.2.0-alpha0025
Changed template to install Cake.Tool preview.
Added something like this:
```
dotnet tool uninstall --global Cake.Tool
dotnet tool install --global \
Cake.Tool \
--add-source https://pkgs.dev.azure.com/cake-build/Cake/_packaging/cake/nuget/v3/index.json \
-version 3.2.0-alpha0025
```
=> manual updates 20231019 - Cake.Tool 3.2.0-alpha0025 setup

cgmanifest.json, config.json, docs/artifact-list-with-versions.md
No.
Updates
- `com.google.guava:guava` - 31.1-android -> 32.0.1-android
- `com.google.errorprone:error_prone_annotations` - 2.20.0 -> 2.21.1
=> Weekly stable updates 20231027

build.cake, build/ci/build.yml, build/ci/setup-environment.yml, build/scripts/update-config.csx, build/scripts/utilities.csx, utilities.cake
No. Infrastructure updates (nugets)
Cake 3.2.0 was released
https://www.nuget.org/packages/Cake.Tool
https://www.nuget.org/packages/Cake.Tool/3.2.0
Bumped nugets for infrastrcuture (CI AzDevOps).
=> Manual updates 20231110 infrastructure - Cake.Tool released 3.2.0

docs/buildtoolsinventory.csv, docs/buildtoolsinventory.md
CI build info (`buildtoolsinventory.*`)
=> buildtoolsinventory updates

cgmanifest.json, config.json, docs/artifact-list-with-versions.md
Updates.
- `org.jetbrains.kotlin:kotlin-reflect` - 1.9.20 -> 1.9.21
- `org.jetbrains.kotlin:kotlin-stdlib` - 1.9.20 -> 1.9.21
- `org.jetbrains.kotlin:kotlin-stdlib-common` - 1.9.20 -> 1.9.21
- `org.jetbrains.kotlin:kotlin-stdlib-jdk7` - 1.9.20 -> 1.9.21
- `org.jetbrains.kotlin:kotlin-stdlib-jdk8` - 1.9.20 -> 1.9.21
- `com.google.errorprone:error_prone_annotations` - 2.21.1 -> 2.23.0
=> Weekly stable updates 20231124

config.json
Context: https://github.com/xamarin/AndroidX/pull/809
Bump all packages so we publish new ones with the `net7.0-android` framework.
=> Bump all packages to add `net7.0-android`.

build/ci/build.yml, nuget-diff.cake
Context: https://github.com/mattleibow/Mono.ApiTools.NuGetDiff/pull/17
Creates a new CI artifact: `api-diff/all-nuget-diff.md`.
This file lists all changes made to the *structure* of NuGet packages built by this repository.  This will help give us extra confidence that we are not accidentally making breaking changes like removing a needed `.targets` file.
This includes:
- Changes to _which_ files are included in the package. (Note this is only presence of files, it does not compare file contents.)
- Changes to NuGet package metadata.
For example, adding support for `net7.0-android` to the `Xamarin.AndroidX.Core` package looks like this:
```
+ lib/net7.0-android33.0/Xamarin.AndroidX.Core.pdb
+ lib/net7.0-android33.0/Xamarin.AndroidX.Core.dll
+ …
```
=> [ci] Add support for generating `nuget-diff.md`.

Directory.Build.props, build.cake, source/AndroidXProject.cshtml, source/Xamarin.Kotlin.StdLib/Additions/InterfacesFixups.cs, source/Xamarin.Kotlin.StdLib/Transforms/Metadata.net7.0-android.xml, source/com.google.crypto.tink/tink-android/Transforms/Metadata.MonoAndroid12.0.xml, source/com.google.crypto.tink/tink-android/Transforms/Metadata.net6.0-android.xml, source/com.google.crypto.tink/tink-android/Transforms/Metadata.xml, templates/kotlin/Project.cshtml, templates/tink/Project.cshtml
We want to use an updated version of `generator` that has `@RestrictTo` support.  This will allow consumers to be warned if they attempt to use API that Google has marked as `internal` using a `@RestrictTo` annotation.
Begin building `net7.0-android` with an updated version of `generator`.  This is accomplished by downloading the `generator` that ships in the .NET Android 8.0 RTM NuGet package.  (`Microsoft.Android.Sdk.Windows` `34.0.43`)  Note it is okay to use the "Windows" package on all platforms because we only use managed cross-platform binaries from the package.  We then set `$(_BindingsToolsLocation)` to point to this package.
There are some transforms and additions changes that only affect this newer version of `generator`, so we also need a way to apply different transform files …
=> Use an updated `generator` for `@RestrictTo` support.

build/ci/build.yml
No.
Increased default timeouts for CI builds to fix builds failing due to timeout
=> Manual updates 20231215 - CI timeouts 300 minutes

build/ci/api-scan.yml, build/ci/build.yml
Context: In January of 2024, the EU will begin enforcing the Digital Markets Act, which, for our purposes, means that any high-volume API calls must be documented, or we must switch to using a documented high-volume API. 
Microsoft's internal "APIScan" ensures that no undocumented APIs are called.
This scan will be run only on Windows `main` builds.  Note that APIScan is run on _binaries_, not _code_, so it must be run in the build stage rather than the compliance stage.
Successful run on a PR build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8815822&view=logs&j=2f7369d1-fb97-5262-a571-f4e9c996b7d1&t=df26002c-a356-594f-dc84-ac5f1cd7aaf1
As expected for an open source, cross-platform project, there does not appear to be any issues found that need to be mitigated.  😁
=> [ci] Add ApiScan.

build/ci/api-scan.yml
Context: https://github.com/xamarin/AndroidX/pull/829
Context: https://github.com/xamarin/xamarin-android/pull/8605
In #829, I got a little ahead of myself with my quote:
> As expected for an open source, cross-platform project, there does not appear to be any issues found that need to be mitigated.
It turns out there were some issues being marked, but the scan doesn't fail the build so they were missed.
Fix 2 things:
- Use @pjcollins's more [complete solution](https://github.com/xamarin/xamarin-android/pull/8605) to store the ApiScan logs and fail the build if any issues were found.
- Fix the following failures by removing some framework assemblies that ship with `dotnet` and we are not redistributing with our packages.
```
system.objectmodel.dll(,): Error documentationnotfound: …
```
=> [ApiScan] Store log files and error on issues.

config.json
updated
- `androidx.activity:activity` - 1.8.1 -> 1.8.2
- `androidx.activity:activity-compose` - 1.8.1 -> 1.8.2
- `androidx.activity:activity-ktx` - 1.8.1 -> 1.8.2
- `androidx.annotation:annotation` - 1.7.0 -> 1.7.1
- `androidx.annotation:annotation-jvm` - 1.7.0 -> 1.7.1
- `androidx.camera:camera-camera2` - 1.3.0 -> 1.3.1
- `androidx.camera:camera-core` - 1.3.0 -> 1.3.1
- `androidx.camera:camera-extensions` - 1.3.0 -> 1.3.1
- `androidx.camera:camera-lifecycle` - 1.3.0 -> 1.3.1
- `androidx.camera:camera-video` - 1.3.0 -> 1.3.1
- `androidx.camera:camera-view` - 1.3.0 -> 1.3.1
- `androidx.cursoradapter:cursoradapter` -  -> 1.0.0
- `androidx.databinding:databinding-adapters` - 8.2.0 -> 8.2.1
- `androidx.databinding:databinding-common` - 8.2.0 -> 8.2.1
- …
=> Weekly stable updates 20240105

config.json, source/AndroidXDirectoryBuildRsp.cshtml
No.
In order to get more information and isolated information the template to generate per project (`csproj`) was added.
Template generates `Directory.Build.rsp` with
- binlogger
- fileloggers
with diagnostic output.
=> Manual updates 20240208 improvements - template for `Directory.Build.rsp`

samples/BuildAll/BuildAll/BuildAll.csproj, samples/BuildAll/BuildAll/Properties/AndroidManifest.xml, samples/BuildMinimalAppCompat/BuildMinimalAppCompat/BuildMinimalAppCompat.csproj, samples/BuildMinimalAppCompat/BuildMinimalAppCompat/Properties/AndroidManifest.xml, samples/BuildMinimalAppCompat/ClassLibrary/ClassLibrary.csproj, samples/BuildMinimalMaterial/BuildMinimalMaterial/ BuildMinimalMaterial.csproj, samples/BuildMinimalMaterial/BuildMinimalMaterial/Properties/AndroidManifest.xml, samples/BuildMinimalMaterial/ClassLibrary/ClassLibrary.csproj, samples/BuildMinimalMaterialAppCompat/BuildMinimalMaterialAppCompat/BuildMinimalMaterialAppCompat.csproj, samples/BuildMinimalMaterialAppCompat/BuildMinimalMaterialAppCompat/Properties/AndroidManifest.xml, samples/BuildMinimalMaterialAppCompat/ClassLibrary/ClassLibrary.csproj, samples/BuildXamarinFormsApp/BuildXamarinFormsApp/BuildXamarinFormsApp.Android/BuildXamarinFormsApp.Android.csproj, samples/BuildXamarinFormsApp/BuildXamarinFormsApp/BuildXamarinFormsApp.Android/Properties/AndroidManifest.xml, samples/dotnet/BuildAllDotNet/AndroidManifest.xml, samples/dotnet/BuildAllDotNet/BuildAllDotNet.csproj, samples/dotnet/BuildAllMauiApp/BuildAllMauiApp.csproj, samples/dotnet/BuildAllXamarinForms/BuildAllXamarinForms.XamarinAndroid/BuildAllXamarinForms.XamarinAndroid.csproj, samples/dotnet/BuildAllXamarinForms/BuildAllXamarinForms.XamarinAndroid/Properties/AndroidManifest.xml
CI builds for samples on windows after tagging and merging into main fail with error on Windows only:
```
D8 : error : java.lang.OutOfMemoryError: Java heap space 
[C:\a\_work\1\s\samples\dotnet\BuildAllDotNet\BuildAllDotNet.csproj::TargetFramework=net7.0-android]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\tools\Xamarin.Android.D8.targets(81[C:\a\_work\1\s\samples\dotnet\BuildAllDotNet\BuildAllDotNet.csproj::TargetFramework=net7.0-android]
MSBUILD : java.exe error JAVA0000: java.lang.OutOfMemoryError [C:\a\_work\1\s\samples\dotnet\BuildAllDotNet\BuildAllDotNet.csproj::TargetFramework=net7.0-android]
MSBUILD : java.exe error JAVA0000:  Java heap space [C:\a\_work\1\s\samples\dotnet\BuildAllDotNet\BuildAllDotNet.csproj::TargetFramework=net7.0-android] …
```
=> Manual updates 20240210 fixes for intermittent CI errors on Windows `java.lang.OutOfMemoryError`

.github/workflows/new-releases-check.yml
Automatic updates fail with:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-dotnet@v3, peter-evans/create-pull-request@v5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
No.
Bumped github action versions.
=> Manual updates 20240216 - automatic version checks and updates version bumps

config.json
Bump all packages so we can ensure .NET 7 versions (with `@RestrictTo` support) have been published.
=> Bump all packages.

build/ci/build.yml, nuget-diff.cake, source/androidx.appcompat/typeforwarders/androidx.appcompat.appcompat-resources-typeforwarders.csproj
After a fresh bump of all packages, there are still 2 issues reported in `api-diff`/`nuget-diff`:
```
+ lib/net7.0-android33.0/Xamarin.AndroidX.AppCompat.Resources.pdb
+ lib/net7.0-android33.0/Xamarin.AndroidX.AppCompat.Resources.dll
+ lib/net7.0-android33.0/Xamarin.AndroidX.AppCompat.Resources.xml
```
This is because this package is manually versioned in a `.csproj`.  Bump this version so we can release a new NuGet.
---
...
This is because our comparison process compares against the highest versioned publicly available NuGet package.  Because we have released a `1.1.0.1-alpha06` version, this is what we compare against, even though we are binding `1.0.0.16` in `main`.
To fix this, add a new `--prefer-released` option to `api-diff` that will choose the highest *stable* package version if …
=> Fix persistent `api-diff` issues.

config.json, utilities.cake
No.
updates
- `androidx.compose.animation:animation-` - 1.6.1 -> 1.6.2
- `androidx.compose.animation:animation-android` - 1.6.1 -> 1.6.2
- `androidx.compose.animation:animation-core` - 1.6.1 -> 1.6.2
- `androidx.compose.animation:animation-core-android` - 1.6.1 -> 1.6.2
- `androidx.compose.animation:animation-graphics` - 1.6.1 -> 1.6.2
- `androidx.compose.animation:animation-graphics-android` - 1.6.1 -> 1.6.2
- `androidx.compose.foundation:foundation` - 1.6.1 -> 1.6.2
- `androidx.compose.foundation:foundation-android` - 1.6.1 -> 1.6.2
- `androidx.compose.foundation:foundation-layout` - 1.6.1 -> 1.6.2
- `androidx.compose.foundation:foundation-layoutandroid` - 1.6.1 -> 1.6.2
- `androidx.compose.material:material` - 1.6.1 -> 1.6.2
- `androidx.compose.material:material-android` - 1.6.1 -> …
=> Weekly stable updates 20240226

build/ci/build.yml
Changing a NuGet version results in the following `nuget-diff` output:
```
- <description>.NET for Android (formerly Xamarin.Android) bindings for AndroidX - animation-android (bindings without managed callable wrappers (C#) and are only used for including Java files) artifact=androidx.compose.animation:animation-android artifact_versioned=androidx.compose.animation:animation-android:1.6.1</description>
+ <description>.NET for Android (formerly Xamarin.Android) bindings for AndroidX - animation-android (bindings without managed callable wrappers (C#) and are only used for including Java files) artifact=androidx.compose.animation:animation-android artifact_versioned=androidx.compose.animation:animation-android:1.6.2</description>
```
We have code that prevents this difference from being …
=> Fix issue causing `nuget-diff.md` noisiness.

config.json, source/androidx.collection/collection/Additions/TypeForwards.cs
Fixes: https://github.com/xamarin/AndroidX/issues/821
Fixes: https://github.com/xamarin/AndroidX/issues/807
In version `1.3.0`, Google moved all the types in `Xamarin.AndroidX.Collection` to `Xamarin.AndroidX.Collection.Jvm`.  While this  is a source compatible change for users, it is not a binary compatible change for users that are relying on NuGets or assemblies that have not been recompiled.
These types will continue to work in Debug builds, but the linker and AOT compiler steps run for Release builds are unable to resolve the moved types, causing unfixable errors (other than recompiling all assemblies).
Adding `[TypeForwardedToAttribute]` attributes allows the linker and AOT to succeed without recompiling old assemblies.
Note this does not imply that we have tooling that can …
=> Add TypeForwards for `Xamarin.AndroidX.Collection`.

build/ci/api-scan.yml
Configures a new [managed identity][0] (MSI) for API Scan, which
allows us to enable a more modern authentication approach when running
API Scan on the `MAUI-1ESPT` agent pool.
A new `$(ApiScanMAUI1ESPTManagedId)` variable has been configured in the
pipeline settings to pass the app ID for this MSI to the API Scan task.
[0]: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cd4829e2-e38b-43d2-8316-2f2009f36f97/resourcegroups/1esobjects/providers/microsoft.managedidentity/userassignedidentities/maui1esptapiscanidentity/overview
Successful CI test run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9310159&view=results
=> [ci] Use managed identity for API scan.

build/ci/build.yml
The NuGet metadata compare for GPS is reporting this diff on nearly every package:
```
- <tags>.NET for Android Xamarin.Android Bindings Google Play Services artifact=com.google.firebase:firebase-common:[Version] artifact_versioned=com.google.firebase:firebase-common:[Version]</tags>
+ <tags>.NET for Android Xamarin.Android Bindings for Google Play Services artifact=com.google.firebase:firebase-common:[Version] artifact_versioned=com.google.firebase:firebase-common:[Version]</tags>
```
It would seem that NuGet.org strips duplicate tags when a package is published, which removes our duplicate `for` tag.  Update our compare to ignore the `for` tag.
=> [private-api-tools] Ignore duplicate "for" package tag.

build/ci/build.yml
After [migrating to the 1ES template](https://github.com/xamarin/AndroidX/pull/844), when our build fails, no logs or artifacts are retained, making it very hard to diagnose the issue.  Add an `always` condition to the output upload so these will get saved.
Example build demonstrating artifacts are uploaded on failure:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9440304&view=results
=> [ci] Ensure logs and artifacts get published on failed builds.

source/androidx.browser/browser/Additions/CustomTabsActivityManager.cs
Fixes https://github.com/xamarin/AndroidX/issues/873
The method `CustomTabsActivityManager.From (Activity parentActivity, string? servicePackageName = null)` caches the passed in `parentActivity` forever, which can cause a memory leak.
Additionally, only the first `parentActivity` passed in supported.  Subsequent `parentActivity` arguments are ignored and the first one is always reused.
Mark this helper method as `[Obsolete]` and recommend consumers implement any desired caching themselves in a way that respects the parent activity(ies) and their lifetimes properly for the relevant application.
=> [AndroidX.Browser] Obsolete CustomTabsActivityManager.From with message describing its shortcomings.

Directory.Build.props, build.cake
Update the version of `generator` used to build the `net7.0-android` version of our packages.
This should contain https://github.com/xamarin/java.interop/pull/1202, which is needed for binding AndroidX Media3.
=> Bump to .NET 8 '8.0.204' generator.

build/scripts/update-config.csx, config.json
We have missed several new versions of `com.google.guava.guava` because they name their release packages like `33.1.0-android`.  Traditionally, adding any sort of label after a hyphen indicates that the package is a pre-release version so we ignore it.  Thus we have been ignoring their new versions.
Fix our update script to allow a pre-release tag of `-android` to count as a stable release version so we will process `guava` updates.
Additionally, go ahead and bump `guava` to the latest version available. Note we remove the `-android` from the NuGet version, as it is not a pre-release package.
=> Fix update script to handle misnamed guava Java versions.

source/AndroidXProject.cshtml
With Classic gone, we can clean up our template a little bit by removing settings that only affected Classic.  Additionally, we can remove some things that aren't getting used due to incorrect `Condition` statements.
This PR should not change our packages in any way.  This is verified by ensuring there are no changes to the `api-diff` or `nuget-diff` files.
---
The `<AndroidJavaSource>` include was already a no-op because `Exists` does not expand wildcards, so the `Condition` was always `false`:
```xml
Condition="Exists('..\..\source\@(Model.MavenGroupId)\@(Model.Name)\java\*.java')"
```
Removing just the `Condition` caused `javac` errors because it was now including `.java` files that were not being included previously.
---
Most everything else was also a no-op because the `Exists` and …
=> Clean up unused legacy parts of the AndroidX project template.

samples/NuGet.config
In order to ensure we are testing the packages built during CI/local build we need to remove the wildcard from `nuget.org`.
With the `nuget.org` wildcard it means that anything that cannot be found locally will be pulled from published packages.  We will never know if we are accidentally pulling a published package instead of the intended local one.
=> [NuGet.config] Remove wildcard from nuget.org.

build/scripts/update-config.csx, config.json
Allow a `comments` field to be used in `config.json`.  This can be used to document reasons for using override features, like why a package is `frozen`.
Additionally, document why all `frozen` artifacts are marked as `frozen`.
=> Allow a 'comments' field to be used in config.json.

cgmanifest.json, config.json, docs/artifact-list-with-versions.md, source/androidx.health/health-services-client/Additions/DebouncedDataTypeCondition.cs, source/androidx.health/health-services-client/Transforms/Metadata.xml
Does this change any of the generated binding API's?
bumped androidx.health from 1.0.0-rc02 to 1.1.0-alpha03
=> bumped androidx.health

BUILDING.md, build.cake, build/cake/update-config.cake, util/Directory.Build.props, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tests/GenerationTests.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tests/Xamarin.AndroidBinderator.Tests.csproj, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/BinderateCommand.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/BumpCommand.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/LegacyCommandLine.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/PublishedCommand.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/SortCommand.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/UpdateCommand.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Program.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Xamarin.AndroidBinderator.Tool.csproj, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/BindingConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/MavenArtifactConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/TemplateConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/ConfigUpdater.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Extensions.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/MavenFactory.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/BindingProjectModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/MavenArtifactModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/NuGetDependencyModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/TemplateSetModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/SolutionFileBuilder.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Util.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj
As the scope of `update-config.csx` has grown, it has become more and more painful that it isn't in an actual project editable in an IDE, making it harder to update or debug.  As it shares code with `binderator`, like reading and writing `config.json`, move the functionality into `binderator`.
To help facilitate running this functionality, add new targets to `cake` for the various operations:
*   `update-config`
Updates config.json to the latest versions found in Maven.
*   `bump-config`
Increments the NuGet patch version of all packages in config.json.
*   `sort-config`
Sorts config.json file using the canonical sort.
*   `published-config`
Shows which NuGet package versions in config.json have been published to NuGet.org.
Note these run the in-tree version of `binderator`, there is no …
=> ﻿Move functionality from `update-config.csx` to `binderator`.

azure-pipelines.yml, build/ci/build-and-test.yml, build/ci/job-extended-tests.yml, build/ci/stage-extended-tests.yml, build/ci/stage-standard-tests.yml, build/ci/variables.yml, tests/allpackages/AllPackagesTests.csproj, tests/allpackages/AllPackagesTests.sln, tests/allpackages/BinderatorConfigFileParser.cs, tests/allpackages/CanonicalError.cs, tests/allpackages/TestAllIndividualPackages.cs
Convert our existing `BuildAllDotNet`/`BuildAllMauiApp` samples to NUnit based unit tests.  These tests use `dotnet new android|maui` instead of committed projects so that we always ensure we are testing against the current templates that our users will be using.
Additionally, move these tests to another stage, so they can run in parallel with other [test suite(s)](https://github.com/xamarin/AndroidX/pull/892).
This PR does not remove the existing `BuildAll*` samples, those will be removed in a future PR.
=> Convert "all packages" "samples" to proper unit tests.

config.json, source/AndroidXProject.cshtml, source/ThirdPartyNotices.cshtml, templates/licenses/android-sdk.txt, templates/licenses/apache-2.0.txt, templates/licenses/bsd.txt, templates/licenses/mit-0.txt, templates/licenses/mit.txt, templates/licenses/sil-1.1.txt, templates/licenses/unicode.txt, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tests/GenerationTests.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/BindingConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/LicenseConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/MavenArtifactConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/BindingProjectModel.cs
Instead of manually maintaining licensing information for packages, pull the license information from the package's POM file.  This information looks like:
```xml
<licenses>
<license>
<name>The Apache Software License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution>
</license>
</licenses>
```
We need to be able to "understand" this license and properties about it, like its SPDX identifier and whether it is proprietary or not.  To do this, we match the license name to a new section in `config.json`:
```json
"licenses": [
{
"name": "The Apache Software License, Version 2.0",
"file": "templates/licenses/apache-2.0.txt",
"spdx": "Apache-2.0",
"proprietary": false
}, ...
]
```
Note there may be multiple entries for the "same" …
=> [binderator] Generate 'THIRD-PARTY-NOTICES' from POM information.

util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Commands/UpdateCommand.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/ConfigUpdater.cs
Make 2 tweaks to the `update-config` console output.  Note these do not affect anything that is written to `config.json`, just what is written to the console.
- Add number of packages and dependencies to table header:
```console
| 340 Packages (* = Has Update)                              | Currently Bound   | Latest Stable   |
|------------------------------------------------------------|-------------------|-----------------|
| androidx.activity.activity                                 | 1.9.1             | 1.9.1           |
...
| 18 Dependencies (* = Has Update)                           | Current Reference | Latest Publish  |
|------------------------------------------------------------|-------------------|-----------------|
| Xamarin.GooglePlayServices.Ads.Identifier …
```
=> [binderator] Tweaks to `update-config` console output.

Directory.Build.props, config.json, nuget-diff.cake, published-namespaces.txt, source/com.google.dagger/dagger/Additions/Additions.cs, source/com.google.dagger/dagger/Transforms/Metadata.xml, source/com.google.inject/guice/Transforms/Metadata.xml, templates/licenses/public-domain.txt, tests/common/NuGet.config
Move the packages in GPS that use the following package-specific templates to this repository and switch them to using the default template:
- annotations
- aopalliance
- dagger
- errorprone
- findbugs
- inject-guice
- jakarta
- javax-inject
- ow2-asm
Companion PR that removes them from GPS: https://github.com/xamarin/GooglePlayServicesComponents/pull/905
=> Move first batch of GPS package-specific templates to AndroidX default template.

azure-pipelines.yml, build/ci/stage-sign-artifacts.yml
Today, when preparing a publish release, the "Sign Archive" step always fails the first run, as it relies on the output from the "Build Windows" job, but does not specify the dependency, so it runs before the packages have been built.
Specifying the dependency is better, but it makes the "Build Windows" stage take a lot longer and the test stage(s) cannot run until it completes.
This PR moves the signing to its own stage with the proper dependency set, so it will not run until the packages are ready.  By moving it to its own stage it can also run in parallel with the test stage(s), reducing the overall CI time.
Test CI run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10231962
=> [ci] Make "Sign Archive" a separate stage.

source/androidx.media3/media3-effect/Transforms/Metadata.xml
Fix for 
https://github.com/xamarin/AndroidX/issues/940
https://github.com/xamarin/AndroidX/issues/940#issuecomment-2350937220
Yes. Surfaces missing API.
Fixed metadata that was removing too much API
=> Fixes for issue 940 [AndroidX.Media3.Transformer] `EditedMediaItem.Bulder` missing

Directory.Build.props
Context: https://github.com/dotnet/android/pull/3554
Creating "reproducible builds" is the current industry best practice for shipping software.
https://reproducible-builds.org/
We should enable `<Deterministic>` to meet this recommendation.
=> Make assemblies deterministic.

.github/ISSUE_TEMPLATE/01-use-package.yml, .github/ISSUE_TEMPLATE/02-new-package.yml, .github/ISSUE_TEMPLATE/03-updated-package.yml, .github/ISSUE_TEMPLATE/04-other.yml, .github/PULL_REQUEST_TEMPLATE.md
We no longer need to ask if this is Classic Xamarin.Android or Android for .NET in the issue template.
Additionally, remove the PR template.  It's outdated (support libraries) and doesn't seem to provide any value, and none of our other repositories have one.
=> [GitHub] Update our new issue templates.

azure-pipelines.yml, config.json, tests/extended/BinderatorConfigFileParser.cs, tests/extended/TestAllIndividualPackages.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/MavenArtifactConfig.cs
- Add `"skipExtendedTests"` to `config.json`.  When set to `true`, the "extended" tests are not run for this package.  This allows us to get our test job green with the packages that currently work.  This way we can go ahead and have it running for currently working packages to ensure they do not regress.
- Set up a "nightly" job that will run the "extended" test suite every night.  Note that this will only run if there have been changes to `main` since the previous run, so it generally won't actually run every night.
Green CI run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10351430
=> Add support for specifying skipping extended tests in config.json.

build.cake, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/BindingProjectConverter.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/BindingProjectDependencyVerifier.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/BindingConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/LicenseConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/MavenArtifactConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/TemplateConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Extensions.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/MavenArtifactDownloader.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/MavenFactory.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/MavenFactory2.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/BindingProjectModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/MavenArtifactModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/NuGetDependencyModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Model/TemplateSetModel.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/SolutionFileBuilder.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Util.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj
Rebase `binderator` on top of `Java.Interop.Tools.Maven` instead of `MavenNet`.  This has 2 benefits:
- Built-in Maven caching so local builds don't have to download the same artifacts every run.
- Better implementations of `MavenVersion` and `MavenVersionRange` that should work for more cases.
This PR also runs `dotnet-format` on `Xamarin.AndroidBinderator` to standardize to our `.editorconfig` settings.
=> [binderator] Rebase on Java.Interop.Tools.Maven.

config.json, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Xamarin.AndroidBinderator.Tool.csproj
We no longer use `binderator` outside of this repository.  Stop building a NuGet package and running package diffs on it to help remove some noise in the diff reports.
=> Don't make a NuGet package for binderator.

config.json, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/BindingProjectConverter.cs
Add support in `binderator` for finding licensing information that is specified in parent POM files.  This allows us to remove all of the hardcoded `overrideLicenses` info currently in `config.json`.
=> [binderator] Add support for licenses specified in parent POMs.

config.json, source/_PackageLevelCustomizations.cshtml, source/_XBDProjectType.cshtml, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/BindingProjectConverter.cs
Update `binderator` to enforce that Java libraries with proprietary licenses are packaged using the `Xamarin.Build.Download` method.
Unfreeze `Xamarin.Google.Android.InstallReferrer` and bind newer versions that are no longer Apache licensed using `"type": "xbd"`.
Additionally, this check found 2 other libraries that are proprietary licensed and should be bound using the `Xamarin.Build.Download` method.  They are updated as well.
=> [binderator] Add check to ensure we use Xamarin.Build.Download for proprietary licensed artifacts.

azure-pipelines.yml, build.cake, build/cake/dotnet-next.cake, build/ci/build.yml, build/ci/setup-environment.yml, build/ci/variables.yml
We waited too late to ensure that this repository builds successfully on .NET 9, causing last-minute fixes in `generator`.  This is something we need to be doing throughout the entire preview cycle, even though we do not ship packages targeting the preview framework.
This PR creates a CI option that can be requested which will run the repository on the preview version of .NET N+1.
Once this test succeeds (hopefully with .NET 9 RTM!) we can enable it as a nightly test to ensure we are continuously testing our .NET previews instead of waiting until the end of the preview cycle.
CI run with this (the failure is expected): https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10401538
=> [ci] Create CI option to test running repository on next version of .NET.

source/com.google.android.gms/play-services-base/Additions/ResultCallbackImpl.cs, source/com.google.android.gms/play-services-basement/Additions/ResultCallbackImpl.cs, source/com.google.android.gms/play-services-tasks/Additions/Task.cs
Fixes https://github.com/xamarin/AndroidX/issues/1018
Fixes instances of:
```
C:\code\AndroidX\source\com.google.android.gms\play-services-tasks\Additions\Task.cs(66,62): warning IL2091: 'TResult' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in 'Android.Runtime.Extensions.JavaCast<TResult>(IJavaObject)'. The generic parameter 'TResult' of 'Android.Gms.Extensions.AwaitableTaskCompleteListener<TResult>' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
C:\code\AndroidX\source\com.google.android.gms\play-services-basement\Additions\ResultCallbackImpl.cs(23,19): warning IL2091: 'TResult' …
```
=> [ILLink] Fix trimmer warnings.

Directory.Build.props, Directory.Build.targets, source/AndroidXProject.cshtml
Suppress the warnings emitted by `generator` by default.  These 19K+ warnings are clearly not things that we intend to take action on, and hide warnings we ***might*** want to take action on.
This is controlled via the `$(_AndroidIgnoreGeneratorWarnings)` property.
If seeing these warnings is desired on a local build, either:
- Change `$(_AndroidIgnoreGeneratorWarnings)` to `false` in the `Directory.Build.props` file.
- Pass it as a build property:
- `dotnet build -p:_AndroidIgnoreGeneratorWarnings=false`
Also fix some `IsTrimmable` warnings by not enabling it on `netstandard2.0` projects.
=> Suppress binding warnings.

build/cake/build-and-package.cake, build/cake/update-config.cake, config.json, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/BindingConfig.cs, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/MavenArtifactConfig.cs
Clean up `config.json`:
- Remove default `dependencyOnly: false` as we only change it for 6 artifacts.
- Move template details to `"default"` `TemplateSet`.
- Add comments for `dependencyOnly: true` artifacts.
- Don't look for dependency versions in the GPS `config.json`.
=> Clean up 'config.json'.

azure-pipelines.yml, build/ci/setup-environment.yml, build/ci/variables.yml, utilities.cake
The Mac pool we use `internal-macos12` is no longer available.  Ideally we could just use the public Azure Pipelines pool, but those machines are underpowered and doubles the (already long!) time taken to build our packages.  Switch to the internal `VSEng-VSMac-Xamarin-Shared` mac pool already in use by `dotnet/android` and MAUI.
`JavaToolInstaller@0` does not seem to work on this image, even though there are many versions of Java SDK already installed on the image.  Set `JAVA_HOME` to Java SDK 11 so we can build.
Additionally, the `tools-executive-oreder-csv-and-markdown` Cake task does not work on these images because it expects `gradle` and other tools to be available in the `$PATH` which they aren't.  As we do not consume or ship these files from the build, add a try/catch block to …
=> [ci] `macos12` is no longer available, use `macos14`.

source/AndroidXProject.cshtml
Add support new nuget package that generates and packs SPDX SBOM into nuget package being built and packaged.
```xml
<PropertyGroup>
<GenerateSBOM>true</GenerateSBOM>
</PropertyGroup>
<ItemGroup>
<PackageReference Include="Microsoft.Sbom.Targets" Version="3.0.0">
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
</ItemGroup>
```
SBOM can be found
```
./_manifest/spdx_2.2/manifest.spdx.json
```
https://github.com/microsoft/sbom-tool
https://devblogs.microsoft.com/engineering-at-microsoft/microsoft-open-sources-software-bill-of-materials-sbom-generation-tool/
https://devblogs.microsoft.com/engineering-at-microsoft/generating-software-bills-of-materials-sboms-with-spdx-at-microsoft/ …
=> Manual updates 20241120 NuGet SBOM generation

tests/extended/TestAllIndividualPackages.cs
Calling `dotnet add nuget <package>` implicitly does a NuGet restore before returning.
However, after we get the test set up using these commands we call `dotnet build` which _also_ does a NuGet restore.
Improve performance by opting out of this initial restore and only doing the one at build time.
=> [tests] Add `--no-restore` to `dotnet` invocations for better performance.

azure-pipelines.yml
Adds dev branches to the CI trigger to kick off builds on these branches
automatically now that PR build restrictions are in place for GitHub
repos.
=> [ci] Add dev/* branches to CI trigger

source/androidx.appcompat/typeforwarders/androidx.appcompat.appcompat-resources-typeforwarders.csproj, source/com.google.android.material/Xamarin.Google.Android.Material.Extensions/Xamarin.Google.Android.Material.Extensions.csproj
1. Replaced
```xml
<Project Sdk="Xamarin.Legacy.Sdk">
```
with:
```xml
<Project Sdk="Microsoft.NET.Sdk">
```
2. Additional cleanup
=> Manual Updates 20250205 SDK type fixes for missed projects

Directory.Build.props, source/com.google.android.gms/play-services-basement/buildtasks/Basement-BuildTasks.csproj, util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj, util/Xamarin.Build.Download/source/Xamarin.Build.Download.Tests/Xamarin.Build.Download.Tests.csproj, util/Xamarin.Build.Download/source/Xamarin.Build.Download/Xamarin.Build.Download.csproj
Context: https://github.com/advisories/GHSA-8g4q-xg66-9fp4
Context: https://github.com/advisories/GHSA-hq7w-xv5x-g34j
Consolidates the MSBuild package reference version into a shared prop
and bumps it to the latest to bring in a newer System.Text.Json and
Microsoft.IO.Redist.
Adds a System.Text.Json reference to Xamarin.AndroidBinderator.csproj to
pull in the latest version of that package with the CVE fix.
=> [build] Address CVE-2024-43485, CVE-2024-38081

source/AndroidXProject.cshtml
disabling `Microsoft.Sbom.Targets` nuget and SBOM generation due to intermittent hangs on MacOSX
Details
https://github.com/microsoft/sbom-tool/issues/946
=> Manual updates 20250224 disabling `Microsoft.Sbom.Targets` nuget and SBOM generation

README.md, source/AndroidXNuGetReadMe.cshtml, source/AndroidXProject.cshtml
Clarify a few documentation issues that have come up:
- Ensure our package information explicitly lists MAUI, as that is the most likely project type users will have.
- Port over the note about GPS package versions having a prepended "1" now that the repos are combined.
=> Clarify a few documentation issues.

azure-pipelines.yml
PR builds are run out of the public azure-pipelines-public.yml pipeline.
=> [ci] Remove PR triggers from azure-pipelines.yml

.gitignore, build/cake/binderate.cake, build/cake/build-and-package.cake, build/ci/build.yml, build/ci/setup-environment.yml, build/scripts/provision-android/provision-android.csproj, source/_PackageLevelCustomizations.cshtml, utilities.cake
Taking a set of unrelated changes we can bring to main.
This will make the diff in #1118 easier to review.
=> Smaller set of changes from #1118

config.json
Context: https://github.com/dotnet/android-libraries/pull/1148
Context: https://www.nuget.org/packages/Xamarin.AndroidX.Emoji2/1.2.0.2
When multi-targeting .NET 8 and 9, I got the error:
generated\androidx.emoji2.emoji2-emojipicker\androidx.emoji2.emoji2-emojipicker.csproj :
error NU1102: Unable to find package Xamarin.AndroidX.Emoji2 with version (>= 1.2.0.3 && < 1.2.1)
`Xamarin.AndroidX.Emoji2` version 1.2.0.3 doesn't actually exist?!?
I am not 100% sure why this failed when adding .NET 9, as the block in `config.json` seems wrong:
"nugetVersion": "1.2.0.3",
We should just fix this in `main`, as it will cause some other issue down the line.
=> Fix `NU1102` error for `Xamarin.AndroidX.Emoji2`

azure-pipelines-public.yml, build/ci/build.yml, build/ci/setup-environment.yml
I'm still seeing the same error as bc19e528, and I noticed:
-p:AndroidSdkDirectory=C:\Android\android-sdk
Which is passed in on macOS...
I setup the `androidSdkRoot` parameter to be set to this value on macOS:
$(Agent.TempDirectory)/android-sdk
=> [ci] set proper `androidSdkRoot` for macOS

azure-pipelines-public.yml, build/ci/build.yml, build/ci/setup-environment.yml, build/scripts/provision-android/provision-android.csproj
I'm still setting the wrong Android SDK used on macOS in some cases: `C:\Android\android-sdk`
Let's use `$(Agent.TempDirectory)/android-sdk`, even on Windows.
=> [ci] use `$(Agent.TempDirectory)/android-sdk` on all platforms

build/ci/build-and-test.yml, global.json
Context: https://discord.com/channels/732297728826277939/732297837953679412/1383008897266352260
To get CI working and producing `net8.0-android;net10.0-android` packages:
* Revert dd6bdd27
* Run `--target=build-android-libraries-net10-net8` again
=> Restore CI, to be able to release latest packages

config.json
In an effort to make this repo more maintainable...
This removes packages, in which:
* There are no (or very little) downloads in the last 90 days
* There are no dependent packages listed on NuGet.org
We are mostly focusing on obscure Xamarin.Firebase packages that no one is using.
* https://www.nuget.org/packages/Xamarin.Android.Google.BillingClient.Ktx
* https://www.nuget.org/packages/Xamarin.AndroidX.Lifecycle.ReactiveStreams.Ktx
* https://www.nuget.org/packages/Xamarin.AndroidX.Paging.RxJava2.Ktx
* https://www.nuget.org/packages/Xamarin.AndroidX.Wear.WatchFace.Complications.Data.Source.Ktx
* https://www.nuget.org/packages/Xamarin.Firebase.Ads.Lite
* https://www.nuget.org/packages/Xamarin.Firebase.Analytics.Ktx
* https://www.nuget.org/packages/Xamarin.Firebase.AppCheck.Debug
* …
=> Remove obscure and/or unused packages

Directory.Build.props, build/ci/variables.yml, util/Directory.Build.props
Update to:
* .NET SDK 9.0.303
* .NET SDK 10.0.100-preview.6.25358.103
I also removed a couple values that were unused that would cause confusion: `dotnetWorkloadSource` and `dotnetNextApiLevel`.
=> [build] update to .NET 10 Preview 6

util/Xamarin.Build.Download/source/Xamarin.Build.Download.Tests/Helpers/TestsBase.cs, util/Xamarin.Build.Download/source/Xamarin.Build.Download.Tests/Xamarin.Build.Download.Tests.csproj
Tests randomly started failing due to:
System.Exception : Could not find 7zip.exe in Xamarin installation
These fail on PRs, but succeed on CI for main and release branches.
Let's ignore the tests for now, as we haven't changed anything to break Xamarin.Build.Download.
=> [tests] ignore failures if `7zip.exe` is not found

build/ci/setup-environment.yml
Builds on the `main` branch fail with:
ERROR: JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/microsoft-21.jdk/Contents/Home
The current code is checking the `$(Agent.Name)`, but it should just check if the directory exists.
=> [build] check if `$(JAVA_HOME_21_X64)` exists instead of agent name

util/Xamarin.Build.Download/source/Xamarin.Build.Download.Tests/Helpers/TestsBase.cs
This prevents flaky CI on test failures such as:
Unexpected error: Download failed. Please download https://search.maven.org/remotecontent?filepath=com/facebook/android/facebook-android-sdk/4.17.0/facebook-android-sdk-4.17.0.aar to a file called C:\Users\cloudtest\AppData\Local\Temp\tmpaazgjb.tmp\unpacked\FacebookAndroid-4.17.0.aar.
Stack trace
at Xamarin.ContentPipeline.Tests.TestsBase.AssertNoMessagesOrWarnings(MSBuildTestLogger logger, String[] ignorePatterns) in C:\a\_work\1\s\util\Xamarin.Build.Download\source\Xamarin.Build.Download.Tests\Helpers\TestsBase.cs:line 71
at NativeLibraryDownloaderTests.Test.TestUncompressedNamedDownload() in C:\a\_work\1\s\util\Xamarin.Build.Download\source\Xamarin.Build.Download.Tests\Test.cs:line 181
at System.RuntimeMethodHandle.InvokeMethod(Object …
=> [tests] ignore tests with `Download failed. Please download...`

build/ci/stage-sign-artifacts.yml
Signing *appears* to be working, but times out at about 2 hours.
We increased this to 120 minutes in 7087b1e2.
Let's increase the timeout further to 180 minutes to see if that helps.
=> [build] increase timeout for signing
